// Package clidoc renders the cobra command tree into ONE markdown page,
// docs/reference/cli-commands.md: the generated companion of the
// hand-written docs/reference/cli.md. `go run ./hack/gen-cli-docs` writes
// it; TestCommittedReferenceIsCurrent fails when the committed page lags
// the tree, the same way the assets drift gate holds the embedded mirror.
// The binary does not link this package (cobra/doc pulls in a markdown
// renderer), so the size gate is untouched.
package clidoc

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

// Title is the page title (VitePress frontmatter).
const Title = "CLI commands"

// header opens the page. The frontmatter title is what the sidebar shows;
// the note says where the text comes from so nobody edits the page by
// hand.
const header = `---
title: ` + Title + `
---

# CLI commands

Every command of the ` + "`lo`" + ` binary with its flags and examples, generated from
the command tree (` + "`go run ./hack/gen-cli-docs`" + `, checked by ` + "`go test ./internal/clidoc/`" + `).
Do not edit this file: change the command's help text and regenerate. The
hand-written [CLI reference](./cli) explains the commands; this page lists them.
The global flags are listed once, under [lo](#lo).

`

// Generate renders root and every visible descendant, depth first in help
// order, as one markdown document. Links between commands become
// same-page anchors.
func Generate(root *cobra.Command) ([]byte, error) {
	root.InitDefaultHelpCmd()
	root.InitDefaultCompletionCmd()
	var buf bytes.Buffer
	buf.WriteString(header)
	if err := gen(root, &buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// inheritedOptions opens the section cobra repeats under every command:
// the global flags, which the page lists once under `## lo`.
const inheritedOptions = "### Options inherited from parent commands\n\n```\n"

// gen writes cmd and then its visible children.
func gen(cmd *cobra.Command, buf *bytes.Buffer) error {
	cmd.DisableAutoGenTag = true
	var one bytes.Buffer
	if err := doc.GenMarkdownCustom(cmd, &one, anchor); err != nil {
		return fmt.Errorf("render %s: %w", cmd.CommandPath(), err)
	}
	buf.WriteString(dropInherited(one.String()))
	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		if err := gen(c, buf); err != nil {
			return err
		}
	}
	return nil
}

// dropInherited removes the inherited-options section from one command's
// page, fence included.
func dropInherited(page string) string {
	before, rest, found := strings.Cut(page, inheritedOptions)
	if !found {
		return page
	}
	_, after, found := strings.Cut(rest, "```\n\n")
	if !found {
		return page
	}
	return before + after
}

// anchor maps cobra's per-command file link (`lo_secrets_set.md`) to the
// heading anchor VitePress derives from `## lo secrets set`.
func anchor(link string) string {
	name := strings.TrimSuffix(link, ".md")
	return "#" + strings.ReplaceAll(name, "_", "-")
}
