// Package clidoc renders the cobra command tree into ONE markdown page,
// docs/reference/cli-commands.md: the generated companion of the
// hand-written docs/reference/cli.md. `go run ./hack/gen-cli-docs` writes
// it; TestCommittedReferenceIsCurrent fails when the committed page lags
// the tree, the same way the assets drift gate holds the embedded mirror.
// The binary does not link this package (cobra/doc pulls in a markdown
// renderer), so the size gate is untouched.
package clidoc

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

// Title is the page title (VitePress frontmatter).
const Title = "CLI commands"

// header opens the page. The frontmatter title is what the sidebar shows;
// the note says where the text comes from so nobody edits the page by
// hand.
const header = `---
title: ` + Title + `
---

# CLI commands

Every command of the ` + "`lo`" + ` binary with its flags and examples, generated from
the command tree (` + "`go run ./hack/gen-cli-docs`" + `, checked by ` + "`go test ./internal/clidoc/`" + `).
Do not edit this file: change the command's help text and regenerate. The
hand-written [CLI reference](./cli) explains the commands; this page lists them.
The global flags are listed once, under [lo](#lo).

`

// Generate renders root and every visible descendant, depth first in help
// order, as one markdown document. Links between commands become
// same-page anchors.
func Generate(root *cobra.Command) ([]byte, error) {
	root.InitDefaultHelpCmd()
	root.InitDefaultCompletionCmd()
	var buf bytes.Buffer
	buf.WriteString(header)
	if err := gen(root, &buf); err != nil {
		return nil, err
	}
	return []byte(escapeAngles(buf.String())), nil
}

// escapeAngles hides a placeholder such as <domain> from the site build.
// Help texts write their placeholders in plain prose, and the site reads
// a page as a template, where <domain> opens an element that never closes
// and the build stops. Prose only: inside a fence or an inline code span
// the text is literal already, and an entity there would print as the
// entity.
func escapeAngles(page string) string {
	lines := strings.Split(page, "\n")
	fence := false
	for i, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "```") {
			fence = !fence
			continue
		}
		if !fence {
			lines[i] = escapeAnglesInProse(line)
		}
	}
	return strings.Join(lines, "\n")
}

// escapeAnglesInProse escapes every `<` of one line except inside an
// inline code span. A span opens with a run of backticks and closes with
// the next run of the same length; a run that never closes is text.
func escapeAnglesInProse(line string) string {
	var out strings.Builder
	for i := 0; i < len(line); {
		if line[i] != '`' {
			if line[i] == '<' {
				out.WriteString("&lt;")
			} else {
				out.WriteByte(line[i])
			}
			i++
			continue
		}
		open := backtickRun(line, i)
		if end := spanEnd(line, i+open, open); end > 0 {
			out.WriteString(line[i:end])
			i = end
			continue
		}
		out.WriteString(line[i : i+open])
		i += open
	}
	return out.String()
}

// backtickRun counts the backticks that start at i.
func backtickRun(line string, i int) int {
	n := 0
	for i+n < len(line) && line[i+n] == '`' {
		n++
	}
	return n
}

// spanEnd returns the index just past the run of want backticks that
// closes a span, or 0 when the line has none.
func spanEnd(line string, from, want int) int {
	for i := from; i < len(line); {
		if line[i] != '`' {
			i++
			continue
		}
		n := backtickRun(line, i)
		if n == want {
			return i + n
		}
		i += n
	}
	return 0
}

// inheritedOptions opens the section cobra repeats under every command:
// the global flags, which the page lists once under `## lo`.
const inheritedOptions = "### Options inherited from parent commands\n\n```\n"

// gen writes cmd and then its visible children.
func gen(cmd *cobra.Command, buf *bytes.Buffer) error {
	cmd.DisableAutoGenTag = true
	var one bytes.Buffer
	if err := doc.GenMarkdownCustom(cmd, &one, anchor); err != nil {
		return fmt.Errorf("render %s: %w", cmd.CommandPath(), err)
	}
	buf.WriteString(dropInherited(one.String()))
	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		if err := gen(c, buf); err != nil {
			return err
		}
	}
	return nil
}

// dropInherited removes the inherited-options section from one command's
// page, fence included.
func dropInherited(page string) string {
	before, rest, found := strings.Cut(page, inheritedOptions)
	if !found {
		return page
	}
	_, after, found := strings.Cut(rest, "```\n\n")
	if !found {
		return page
	}
	return before + after
}

// anchor maps cobra's per-command file link (`lo_secrets_set.md`) to the
// heading anchor VitePress derives from `## lo secrets set`.
func anchor(link string) string {
	name := strings.TrimSuffix(link, ".md")
	return "#" + strings.ReplaceAll(name, "_", "-")
}
