package clidoc

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/kernpilot/lok8s/internal/cli"
	"github.com/kernpilot/lok8s/internal/config"
	"github.com/kernpilot/lok8s/internal/testutil"
)

// Page is the committed page, relative to the repository root.
const Page = "docs/reference/cli-commands.md"

// TestCommittedReferenceIsCurrent is the drift gate: the committed page
// equals what the tree renders now. Regenerate with
// `go run ./hack/gen-cli-docs` (or `make docs-cli`).
func TestCommittedReferenceIsCurrent(t *testing.T) {
	root := cli.NewRoot(&config.Paths{Base: t.TempDir()})
	got, err := Generate(root)
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(testutil.RepoRoot(t), Page)
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("%s: %v (run: go run ./hack/gen-cli-docs)", Page, err)
	}
	if string(want) != string(got) {
		t.Errorf("%s is stale (run: go run ./hack/gen-cli-docs, then commit it)\n%s", Page, testutil.FirstDiff(string(want), string(got)))
	}
}

// TestGenerateShape pins what the page must carry: one heading per visible
// command, the completion command, same-page anchors, no cobra timestamp.
func TestGenerateShape(t *testing.T) {
	root := cli.NewRoot(&config.Paths{Base: t.TempDir()})
	got, err := Generate(root)
	if err != nil {
		t.Fatal(err)
	}
	page := string(got)
	for _, heading := range []string{"## lo\n", "## lo use\n", "## lo secrets set\n", "## lo completion bash\n", "## lo drivers lo status\n"} {
		if !strings.Contains(page, heading) {
			t.Errorf("page lacks %q", heading)
		}
	}
	for _, absent := range []string{"## lo hooks", "## lo operator", "## lo k8s", "Auto generated by spf13/cobra", ".md)", "Options inherited from parent commands"} {
		if strings.Contains(page, absent) {
			t.Errorf("page carries %q", absent)
		}
	}
	if !strings.Contains(page, "(#lo-secrets)") {
		t.Errorf("page lacks the same-page anchor #lo-secrets")
	}
	// The global flags appear once, under the root.
	if n := strings.Count(page, "--no-eject"); n != 1 {
		t.Errorf("--no-eject appears %d times, want once (under ## lo)", n)
	}
	if !strings.Contains(page, "### Examples\n\n```\n  lo use\n  lo use kubehz.dev\n```") {
		t.Errorf("page lacks the lo use example block")
	}
}

// TestPlaceholdersAreEscapedForTheSite pins what broke the docs deploy:
// a help text writes a placeholder in plain prose, the page carried it
// verbatim, and the site build stopped at an element that never closes.
// Prose is escaped, a code span and a fence keep their text.
func TestPlaceholdersAreEscapedForTheSite(t *testing.T) {
	for _, c := range []struct{ name, in, want string }{
		{"prose", "clusters/<domain>/cluster.lok8s.yaml", "clusters/&lt;domain>/cluster.lok8s.yaml"},
		{"code span", "write `lo init <domain>` first", "write `lo init <domain>` first"},
		{"mixed", "`a<b` and c<d", "`a<b` and c&lt;d"},
		{"double backticks", "``x`<y`` and <z", "``x`<y`` and &lt;z"},
		{"unclosed span", "a `b and <c", "a `b and &lt;c"},
		{"fence", "```\n<domain>\n```", "```\n<domain>\n```"},
	} {
		t.Run(c.name, func(t *testing.T) {
			if got := escapeAngles(c.in); got != c.want {
				t.Errorf("escapeAngles(%q)\n got %q\nwant %q", c.in, got, c.want)
			}
		})
	}
}
