#!/usr/bin/env bats
# crds_test.bats — unit tests for .lok8s/libs/crds (CRD source-of-truth generator)
#
# The committed operator/crds/*.yaml are GENERATED from operator/crds/schema/*.
# These tests pin two invariants: (1) the committed CRDs are never stale vs their
# schema (the same drift gate CI runs via `lo crds check`), and (2) generate /
# check round-trip correctly in a sandbox.

setup() {
  load "../test_helper"
  setup_tmpdir

  command -v yq &>/dev/null || skip "yq required for crds tests"

  # Stub argsh's import (the lib only imports ^utils/verbose, already sourced).
  import() { :; }
  export -f import
  source "${_PROJECT_ROOT}/.lok8s/utils/verbose.sh"
  source "${_PROJECT_ROOT}/.lok8s/libs/crds"
}

teardown() {
  teardown_tmpdir
}

# --- the real drift gate (what CI enforces) ---

@test "committed operator/crds are in sync with their schema" {
  CRD_SCHEMA_DIR="${_PROJECT_ROOT}/operator/crds/schema"
  CRD_OUT_DIR="${_PROJECT_ROOT}/operator/crds"
  run crds::check
  assert_success
  assert_output --partial "up to date"
}

@test "every committed cluster kind has a schema source" {
  for kind in lo capi kkp kubeone deploy; do
    [[ -f "${_PROJECT_ROOT}/operator/crds/schema/${kind}.schema.yaml" ]] \
      || fail "missing schema for ${kind}"
    [[ -f "${_PROJECT_ROOT}/operator/crds/${kind}.yaml" ]] \
      || fail "missing generated CRD for ${kind}"
  done
}

@test "generated CRDs all share the cluster.lok8s.dev group" {
  for kind in lo capi kkp kubeone deploy; do
    run yq -r '.spec.group' "${_PROJECT_ROOT}/operator/crds/${kind}.yaml"
    assert_output "cluster.lok8s.dev"
  done
}

# --- sandbox round-trip ---

_sandbox() { # copy real schemas into a writable sandbox, point the lib at it
  CRD_SCHEMA_DIR="${BATS_TEST_TMPDIR}/schema"
  CRD_OUT_DIR="${BATS_TEST_TMPDIR}/out"
  mkdir -p "${CRD_SCHEMA_DIR}" "${CRD_OUT_DIR}"
  cp "${_PROJECT_ROOT}"/operator/crds/schema/*.schema.yaml "${CRD_SCHEMA_DIR}/"
}

@test "generate writes one CRD per schema, then check passes" {
  _sandbox
  run crds::generate
  assert_success
  for kind in lo capi kkp kubeone deploy; do
    [[ -f "${CRD_OUT_DIR}/${kind}.yaml" ]] || fail "generate skipped ${kind}"
  done
  run crds::check
  assert_success
}

@test "generated CRD carries the DO-NOT-EDIT banner" {
  _sandbox
  crds::generate
  run head -1 "${CRD_OUT_DIR}/lo.yaml"
  assert_output --partial "GENERATED by 'lo crds generate'"
}

@test "generated CRD metadata.name is <plural>.<group>" {
  _sandbox
  crds::generate
  run yq -r '.metadata.name' "${CRD_OUT_DIR}/kubeone.yaml"
  assert_output "kubeones.cluster.lok8s.dev"
}

@test "check fails when a generated CRD drifts from its schema" {
  _sandbox
  crds::generate
  echo "  hand-edited: true" >> "${CRD_OUT_DIR}/lo.yaml"
  run crds::check
  assert_failure
  assert_output --partial "STALE"
}

@test "preserve-unknown-fields survives the generate round-trip" {
  _sandbox
  crds::generate
  # The spec-level x-kubernetes-preserve-unknown-fields guard must not be
  # dropped by the yq transform (losing it = silent field pruning on write).
  run yq -r \
    '.spec.versions[0].schema.openAPIV3Schema.properties.spec["x-kubernetes-preserve-unknown-fields"]' \
    "${CRD_OUT_DIR}/lo.yaml"
  assert_output "true"
}
