package spec

import (
	"gopkg.in/yaml.v3"

	"github.com/kernpilot/lok8s/kustomize/pkg/kyaml"
)

// BashEntry is the spec for a secret value generated by running a
// shell command or script. The output is cached like passwd: entries —
// the command runs once, the result is stored in $PATH_SECRETS, and
// subsequent builds reuse the cached value.
//
// Shorthand forms:
//
//	OIDC_KEY: "openssl genrsa 4096"          # string → exec
//
// Full mapping:
//
//	OIDC_KEY:
//	  exec: "openssl genrsa 4096"            # inline command (bash -c)
//	  output: stdout                          # stdout (default) | stderr | combined
//
//	CERT_BUNDLE:
//	  file: "${PATH_BASE}/scripts/gen.sh"    # script file (bash <file>)
//	  output: stdout
type BashEntry struct {
	// Exec is an inline shell command run via bash -c.
	// Mutually exclusive with File.
	Exec string `yaml:"exec,omitempty"`

	// File is a path to a script file run via bash.
	// Supports envsubst-style ${VAR} expansion via the plugin's env
	// lookup (PATH_BASE, PATH_SECRETS, etc.).
	// Mutually exclusive with Exec.
	File string `yaml:"file,omitempty"`

	// Output selects which stream to capture as the secret value.
	// "stdout" (default), "stderr", or "combined".
	Output string `yaml:"output,omitempty"`

	// Newline controls the trailing LINE TERMINATOR (\r/\n only — not spaces or
	// tabs). Applied AFTER Encode, so for encoded output it operates on the
	// (text) base64/hex value — binary is preserved. For raw (un-encoded) binary
	// that must be byte-exact, use "keep".
	// "strip" (default) — remove trailing newline(s)
	// "keep"            — preserve output exactly as produced
	// "ensure"          — exactly one trailing newline
	Newline string `yaml:"newline,omitempty"`

	// Encode transforms the output. Applied BEFORE Newline so the exact command
	// bytes are encoded (stripping raw bytes first would corrupt binary keys).
	// "" (default)  — raw bytes, no encoding
	// "base64"      — standard base64
	// "hex"         — lowercase hex
	Encode string `yaml:"encode,omitempty"`

	// Update, when true, bypasses the cache: the command runs on EVERY build and
	// overwrites the cached value, instead of the default run-once-then-reuse.
	// Use for values bound to LIVE cluster state that go stale when the cluster
	// is recreated — e.g. an in-cluster kubeconfig that embeds the current
	// cluster CA + admin client cert (a fresh `lo up` mints new ones, so a cached
	// copy authenticates against the old cluster). Mirrors the env: generator's
	// `update`. Does not affect the entry hash, so it needs no re-`lo secrets allow`.
	Update bool `yaml:"update,omitempty"`
}

// bashEntryRaw avoids infinite recursion in UnmarshalYAML.
type bashEntryRaw BashEntry

// UnmarshalYAML accepts a shorthand string (= exec) or a full mapping.
func (b *BashEntry) UnmarshalYAML(node *yaml.Node) error {
	switch node.Kind {
	case yaml.ScalarNode:
		// String shorthand → exec
		b.Exec = node.Value
		if b.Exec == "" {
			return kyaml.NodeErrf(node, "bash shorthand must be a non-empty command string")
		}
		return nil
	case yaml.MappingNode:
		var raw bashEntryRaw
		if err := kyaml.DecodeNodeStrict(node, &raw); err != nil {
			return err
		}
		*b = BashEntry(raw)
		if b.Exec == "" && b.File == "" {
			return kyaml.NodeErrf(node, "bash entry must have exec or file")
		}
		if b.Exec != "" && b.File != "" {
			return kyaml.NodeErrf(node, "bash entry cannot have both exec and file")
		}
		switch b.EffectiveOutput() {
		case "stdout", "stderr", "combined":
		default:
			return kyaml.NodeErrf(node, "bash output must be stdout, stderr, or combined; got %q", b.Output)
		}
		switch b.EffectiveNewline() {
		case "strip", "keep", "ensure":
		default:
			return kyaml.NodeErrf(node, "bash newline must be strip, keep, or ensure; got %q", b.Newline)
		}
		switch b.EffectiveEncode() {
		case "", "base64", "hex":
		default:
			return kyaml.NodeErrf(node, "bash encode must be base64, hex, or empty; got %q", b.Encode)
		}
		return nil
	default:
		return kyaml.NodeErrf(node, "bash entry must be string or mapping, got %s", nodeKindString(node.Kind))
	}
}

// EffectiveOutput returns the configured output stream or "stdout".
func (b BashEntry) EffectiveOutput() string {
	if b.Output == "" {
		return "stdout"
	}
	return b.Output
}

// EffectiveNewline returns the configured newline mode or "strip".
func (b BashEntry) EffectiveNewline() string {
	if b.Newline == "" {
		return "strip"
	}
	return b.Newline
}

// EffectiveEncode returns the configured encoding or "" (no encoding).
func (b BashEntry) EffectiveEncode() string {
	return b.Encode
}
