package toolchain

// template.go — the consumer .bin/b.yaml `lo init toolchain` writes. The
// pins are the constants in pins.go (drift-tested against go.mod); lo's own
// version stamps the Secret-plugin entry so a project always installs the
// generator its `lo` was built with.

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Marker is the header line that identifies a b.yaml written by `lo init
// toolchain`. `lo doctor` verifies the pinned toolchain by default only
// when it is present (a hand-written or profile-synced b.yaml is not
// checked unless --toolchain asks), and the file is never overwritten.
const Marker = "# lo-toolchain: managed pins — written by `lo init toolchain`"

// Groups a consumer selects. core is always on: it is what every `lo`
// path execs.
const (
	GroupCore  = "core"
	GroupLocal = "local"
	GroupCloud = "cloud"
)

// DefaultGroups is the `lo init toolchain` default selection.
var DefaultGroups = []string{GroupCore, GroupLocal}

// TemplateOptions shapes one generated b.yaml.
type TemplateOptions struct {
	// Name heads the file (the project name).
	Name string
	// LoVersion is the version of the running lo (assets.Version()),
	// with or without the leading v; it pins the Secret plugin asset.
	LoVersion string
	// Variant names the build ("core" / "full") in the header.
	Variant string
	// Groups selects which entries are active; entries of other groups are
	// emitted commented out. core is implied.
	Groups []string
}

// entry is one binaries: item of the template.
type entry struct {
	key     string
	group   string
	comment string   // leading comment lines (without the "# ")
	fields  []string // "key: value" lines, already ordered
}

// entries is the consumer toolchain, in emission order: core (kubectl +
// the three render tools), local (the kind + Tilt dev loop), cloud (the
// provisioning drivers).
func entries(loVersion string) []entry {
	return []entry{
		{key: "kubectl", group: GroupCore, fields: nil},
		{key: "kustomize", group: GroupCore,
			comment: "The renderer. lo core execs it (lo build, the addon render); lo-full carries the\nsame release in-process and only needs it for LO_RENDER=exec.",
			fields:  []string{"version: " + KustomizeCLI}},
		{key: "github.com/mgoltzsche/khelm", group: GroupCore,
			comment: "khelm — the kustomize exec plugin that inflates the Helm charts the addons use.\nInstalled as a FILE under .kustomize/ (KUSTOMIZE_PLUGIN_HOME), not on PATH.",
			fields:  []string{"version: v" + KhelmVersion, "file: ../.kustomize/" + ChartRendererPluginRel}},
		{key: "github.com/kernpilot/lok8s", group: GroupCore,
			comment: "secrets.lok8s.dev/v1/Secret — lok8s' own generator, shipped with every lok8s\nrelease as kustomize-secret-<os>-<arch>; pinned to the version of THIS lo.",
			fields:  []string{"version: " + vPrefixed(loVersion), "asset: kustomize-secret-*", "file: ../.kustomize/" + SecretPluginRel}},
		{key: "kind", group: GroupLocal},
		{key: "tilt", group: GroupLocal},
		{key: "mkcert", group: GroupLocal},
		{key: "github.com/kubermatic/kubeone", group: GroupCloud},
		{key: "hcloud", group: GroupCloud},
	}
}

var groupTitles = map[string]string{
	GroupCore:  "core: what `lo` execs on every path",
	GroupLocal: "local: the kind + Tilt dev loop (lo up, lo tilt, lo trust)",
	GroupCloud: "cloud: the provisioning drivers (KubeOne on Hetzner) — opt-in",
}

var groupOrder = []string{GroupCore, GroupLocal, GroupCloud}

// vPrefixed normalizes a version to the tag form b matches ("v0.3.0").
func vPrefixed(v string) string {
	v = strings.TrimSpace(v)
	if v == "" || v == "dev" {
		return "v" + v
	}
	if strings.HasPrefix(v, "v") {
		return v
	}
	return "v" + v
}

// NormalizeGroups validates a --groups selection: known names only, core
// implied, order canonical.
func NormalizeGroups(groups []string) ([]string, error) {
	set := map[string]bool{GroupCore: true}
	for _, g := range groups {
		g = strings.TrimSpace(strings.ToLower(g))
		if g == "" {
			continue
		}
		if _, ok := groupTitles[g]; !ok {
			return nil, fmt.Errorf("unknown toolchain group %q (want core, local, cloud)", g)
		}
		set[g] = true
	}
	var out []string
	for _, g := range groupOrder {
		if set[g] {
			out = append(out, g)
		}
	}
	return out, nil
}

// Template renders the b.yaml.
func Template(o TemplateOptions) string {
	groups := DefaultGroups
	if len(o.Groups) > 0 {
		if g, err := NormalizeGroups(o.Groups); err == nil {
			groups = g
		}
	}
	active := map[string]bool{}
	for _, g := range groups {
		active[g] = true
	}
	name := o.Name
	if name == "" {
		name = "lok8s project"
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# %s — the lok8s toolchain, managed by b (github.com/fentas/b · binary.help).\n", name)
	b.WriteString(Marker + "\n")
	fmt.Fprintf(&b, "# Generated by lo %s (%s); `lo init toolchain` never overwrites this file, it\n", vPrefixed(o.LoVersion), o.Variant)
	b.WriteString("# prints a diff. Run `.bin/b install` to (re)install; `lo doctor` verifies what landed.\n")
	b.WriteString("#\n")
	b.WriteString("# Pins: the three tools that SHAPE every rendered manifest — kustomize, the khelm\n")
	b.WriteString("# ChartRenderer and the secrets.lok8s.dev Secret generator — are pinned to the\n")
	b.WriteString("# releases this lo was built and byte-parity-tested against (lo core execs them;\n")
	b.WriteString("# lo-full links the same releases). Bump them together and re-render afterwards:\n")
	b.WriteString("# `lo build` promotes artifacts.yaml only when the bytes change, so a bump that\n")
	b.WriteString("# moves nothing reports \"render unchanged\". Everything else floats (b update).\n")
	b.WriteString("#\n")
	b.WriteString("# Groups are a lok8s convention (b ignores the key): core = what every lo path\n")
	b.WriteString("# execs; local = the kind + Tilt dev loop; cloud = the provisioning drivers.\n")
	b.WriteString("# Entries outside the selected groups are kept below, commented out — uncomment\n")
	b.WriteString("# and `.bin/b install` to opt in (or: lo init toolchain --groups core,local,cloud).\n")
	b.WriteString("#\n")
	b.WriteString("# Not here on purpose: argsh, yq, jq, envsubst, sops, ssh-to-age. The Go binary\n")
	b.WriteString("# links or reimplements them; only the frozen bash implementation (LO_IMPL=bash)\n")
	b.WriteString("# and the provider plugins need them. To run that side, add\n")
	b.WriteString("#   github.com/arg-sh/argsh: {asset: argsh, onPost: \"${B_BIN} builtin ${B_EVENT}\"}\n")
	b.WriteString("#   yq: {}   jq: {}   renvsubst: {alias: envsubst}   sops: {}   ssh-to-age: {}\n")
	b.WriteString("# and `.bin/b install`. Docs: https://lok8s.io/guide/toolchain\n")
	b.WriteString("binaries:\n")
	for _, g := range groupOrder {
		fmt.Fprintf(&b, "  # ── %s\n", groupTitles[g])
		for _, e := range entries(o.LoVersion) {
			if e.group != g {
				continue
			}
			prefix := "  "
			if !active[g] {
				prefix = "  # "
			}
			if e.comment != "" {
				for _, line := range strings.Split(e.comment, "\n") {
					b.WriteString(prefix + "# " + line + "\n")
				}
			}
			if len(e.fields) == 0 {
				fmt.Fprintf(&b, "%s%s:\n", prefix, e.key)
				fmt.Fprintf(&b, "%s  groups: [%s]\n", prefix, g)
				continue
			}
			fmt.Fprintf(&b, "%s%s:\n", prefix, e.key)
			for _, f := range e.fields {
				fmt.Fprintf(&b, "%s  %s\n", prefix, f)
			}
			fmt.Fprintf(&b, "%s  groups: [%s]\n", prefix, g)
		}
		if g != groupOrder[len(groupOrder)-1] {
			b.WriteString("\n")
		}
	}
	return b.String()
}

// HasMarker reports whether a b.yaml carries the lo toolchain marker.
func HasMarker(path string) bool {
	raw, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	for _, line := range strings.Split(string(raw), "\n") {
		if strings.TrimSpace(line) == Marker {
			return true
		}
	}
	return false
}

// PinnedEntries lists the "key → version" pairs the template pins, for
// tests and for doctor's expectation table.
func PinnedEntries(loVersion string) map[string]string {
	out := map[string]string{}
	for _, e := range entries(loVersion) {
		for _, f := range e.fields {
			if v, ok := strings.CutPrefix(f, "version: "); ok {
				out[e.key] = v
			}
		}
	}
	return out
}

// WriteResult reports what Write did with the b.yaml.
type WriteResult struct {
	// Path is the b.yaml location.
	Path string
	// Written is true when the file was created.
	Written bool
	// Diff is the unified diff (existing → generated) when the file
	// already existed and differs; empty when identical.
	Diff string
	// Same is true when an existing file already matches the template.
	Same bool
}

// Write places the template at <bin>/b.yaml unless it exists. An existing
// file is NEVER overwritten (the same rule as ejected assets): the result
// carries a diff against the generated content and the caller prints the
// instructions. DryRun computes the result without touching the tree.
func Write(bin string, content string, dryRun bool) (WriteResult, error) {
	path := filepath.Join(bin, "b.yaml")
	res := WriteResult{Path: path}
	if raw, err := os.ReadFile(path); err == nil {
		if string(raw) == content {
			res.Same = true
			return res, nil
		}
		res.Diff = unifiedDiff("b.yaml (existing)", "b.yaml (lo init toolchain)", string(raw), content)
		return res, nil
	}
	if dryRun {
		return res, nil
	}
	if err := os.MkdirAll(bin, 0o755); err != nil {
		return res, err
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return res, err
	}
	res.Written = true
	return res, nil
}

// unifiedDiff is a small line-based unified diff (LCS), enough for a
// human to see which pins differ. No external dependency.
func unifiedDiff(aName, bName, a, b string) string {
	al := strings.Split(strings.TrimSuffix(a, "\n"), "\n")
	bl := strings.Split(strings.TrimSuffix(b, "\n"), "\n")
	n, m := len(al), len(bl)
	// lcs[i][j] = length of the LCS of al[i:], bl[j:]
	lcs := make([][]int, n+1)
	for i := range lcs {
		lcs[i] = make([]int, m+1)
	}
	for i := n - 1; i >= 0; i-- {
		for j := m - 1; j >= 0; j-- {
			switch {
			case al[i] == bl[j]:
				lcs[i][j] = lcs[i+1][j+1] + 1
			case lcs[i+1][j] >= lcs[i][j+1]:
				lcs[i][j] = lcs[i+1][j]
			default:
				lcs[i][j] = lcs[i][j+1]
			}
		}
	}
	var out strings.Builder
	fmt.Fprintf(&out, "--- %s\n+++ %s\n", aName, bName)
	i, j := 0, 0
	for i < n || j < m {
		switch {
		case i < n && j < m && al[i] == bl[j]:
			out.WriteString(" " + al[i] + "\n")
			i++
			j++
		case i < n && (j == m || lcs[i+1][j] >= lcs[i][j+1]):
			// Deletions before insertions, the way diff -u reads.
			out.WriteString("-" + al[i] + "\n")
			i++
		default:
			out.WriteString("+" + bl[j] + "\n")
			j++
		}
	}
	return out.String()
}

// SortedGroups is the canonical spelling of a group selection for
// messages.
func SortedGroups(groups []string) string {
	g := append([]string{}, groups...)
	sort.Strings(g)
	return strings.Join(g, ",")
}
