# shellcheck shell=bash disable=SC2016,SC2034
# SC2016: single-quoted $ here is jq/yq/awk program text or a remote-script literal
# registries.sh — Registry container lifecycle
# Reads from .registries.json (generated by config-registry.sh)

# lo::registry_http_block — emit the registry `http:` stanza for the
# active mode. The static config YAMLs ship the plain-HTTP block (:80);
# in TLS mode we replace it with a :443 listener referencing the
# mkcert cert+key mounted at LO_REGISTRY_TLS_MOUNT. Indentation matches
# the top-level `http:` key in the registry config (two-space children).
lo::registry_http_block() {
  if registry::is_tls; then
    cat <<EOF
http:
  addr: :${LO_REGISTRY_PORT_TLS}
  tls:
    certificate: ${LO_REGISTRY_TLS_MOUNT}/tls.crt
    key: ${LO_REGISTRY_TLS_MOUNT}/tls.key
  headers:
    X-Content-Type-Options: [nosniff]
EOF
  else
    cat <<EOF
http:
  addr: :${LO_REGISTRY_PORT}
  headers:
    X-Content-Type-Options: [nosniff]
EOF
  fi
}

# lo::render_registry_config — render a registry config file for the
# active mode. Substitutes ${REMOTE_URL} for mirrors and swaps the
# http: block to TLS when enabled. Reads the static file, strips its
# hardcoded http: stanza (the `http:` line plus its indented children),
# and appends the mode-appropriate block.
lo::render_registry_config() {
  local config_file="${1}" url="${2}"

  # Pure-bash placeholder substitution — envsubst is NOT portable here: the
  # b-managed Go envsubst (a8m) rejects gettext's SHELL-FORMAT positional
  # argument with "Unknown flag: ${REMOTE_URL}", silently emptying the config.
  local base
  base=$(cat "${config_file}")
  if [[ -n "${url}" ]]; then
    base="${base//'${REMOTE_URL}'/${url}}"
  fi

  # Drop the existing http: block (top-level key + its 2-space-indented
  # body) so we can re-emit it for the active mode. awk: when we hit a
  # line starting exactly `http:`, skip it and all following lines that
  # are indented (children) until the next top-level key.
  local without_http
  without_http=$(echo "${base}" | awk '
    /^http:/ { skip = 1; next }
    skip && /^[[:space:]]/ { next }
    { skip = 0; print }
  ')

  printf '%s\n%s\n' "${without_http}" "$(lo::registry_http_block)"
}

# ── Registry TLS certificate: the set's docker volume ───────────────────────
# One leaf for the whole registry set, minted by the secrets.lok8s.dev Secret
# plugin (the binary lok8s already ships and requires — no mkcert/certgen) and
# kept in the docker volume <project_network>-registry-tls, next to the set's
# data volumes (<project_network>-registry-<name>). Every registry container
# mounts the volume at LO_REGISTRY_TLS_MOUNT. No project directory holds the
# material (releases before v0.4.0 extracted it to .secrets/tls/registries and
# bind-mounted that directory). The volume is written and read through a
# throwaway container that mounts it (docker container create + docker cp +
# docker rm): the set's own containers may not exist yet. The private key never
# leaves the volume: `lo up` reads tls.crt (the config hash) and .sans (the
# re-mint key); nothing in the cluster consumes the key, the kind nodes trust
# the dev CA through certs.d. Same docker argv, same order as the Go driver
# (internal/driver/lo/registrytls.go): hack/parity-orchestrate.sh diffs the
# argv of both implementations byte for byte.

LO_REGISTRY_TLS_SCRATCH_PREFIX=".registry-tls-tmp."
LO_REGISTRY_TLS_FILES=(tls.crt tls.key .sans)
# The cert the mint read or produced in this process; lo::registries hashes
# it without a second read of the volume.
LO_REGISTRY_TLS_CRT=""

# lo::registry_tls_volume — the set's cert volume.
lo::registry_tls_volume() {
  echo "$(registry::project_network)-registry-tls"
}

# lo::registry_tls_sans — the SAN list, one per line: hostnames first per
# entry, then its IP (framework registries contribute their canonical
# hostname, mirrors the upstream domain they impersonate, every registry its
# IP); deduplicated, order kept.
lo::registry_tls_sans() {
  local -a sans=()
  _lo_registry_san() {
    # reg_domain: keep the per-entry field from shadowing an inherited `domain`.
    local name="${1}" ip="${2}" url="${3}" reg_domain="${4}" host="${5}" type="${6}"
    if [[ -n "${host}" ]]; then sans+=("${host}"); fi
    if [[ -n "${reg_domain}" ]]; then sans+=("${reg_domain}"); fi
    if [[ -n "${ip}" ]]; then sans+=("${ip}"); fi
  }
  registry::each _lo_registry_san
  local -A seen=()
  local s
  for s in "${sans[@]}"; do
    [[ -n "${seen[${s}]:-}" ]] && continue
    seen[${s}]=1
    echo "${s}"
  done
}

# lo::registry_tls_volume_exists <vol>
lo::registry_tls_volume_exists() {
  docker volume inspect -f '{{.Name}}' "${1}" >/dev/null 2>&1
}

# lo::registry_tls_with_volume <vol> <fn> [args…] — run `fn <ctr> [args…]`
# against a throwaway container that mounts the volume (docker cp needs a
# container). The container is removed on every exit.
lo::registry_tls_with_volume() {
  local vol="${1}" fn="${2}"
  shift 2
  local ctr="${vol}-io" err rc=0
  docker rm -f "${ctr}" >/dev/null 2>&1 || true
  if ! err=$(docker container create --name "${ctr}" \
      --volume "${vol}:${LO_REGISTRY_TLS_MOUNT}" "${LO_REGISTRY_IMAGE}" 2>&1 >/dev/null); then
    echo "error: docker container create ${ctr} (volume ${vol}) failed: ${err%%$'\n'*}" >&2
    return 2
  fi
  "${fn}" "${ctr}" "$@" || rc=$?
  docker rm -f "${ctr}" >/dev/null 2>&1 || true
  return "${rc}"
}

# lo::registry_tls_volume_read <ctr> <name> — one file of the mounted volume
# through `docker cp <ctr>:<mount>/<name> -`, a tar stream with that one
# entry. Prints the bytes followed by a \x01 sentinel (so a trailing newline
# survives the caller's $(…)); fails when docker fails or the stream is empty.
lo::registry_tls_volume_read() {
  local ctr="${1}" name="${2}" data status
  data=$(docker cp "${ctr}:${LO_REGISTRY_TLS_MOUNT}/${name}" - 2>/dev/null | tar -xOf - 2>/dev/null; printf '\001%s' "${PIPESTATUS[0]}")
  status="${data##*$'\001'}"
  data="${data%$'\001'*}"
  [[ "${status}" == "0" && -n "${data}" ]] || return 1
  printf '%s\001' "${data}"
}

# lo::registry_tls_volume_pem <ctr> <name> [type] — the file read from the
# mounted volume, only when it is a PEM block (of the given type when set):
# an empty, truncated or non-PEM file (a crash mid `docker cp`) counts as
# missing. Prints the bytes + the \001 sentinel like
# lo::registry_tls_volume_read.
lo::registry_tls_volume_pem() {
  local ctr="${1}" name="${2}" type="${3:-}" data
  data=$(lo::registry_tls_volume_read "${ctr}" "${name}") || return 1
  [[ "${data%$'\001'}" == "-----BEGIN ${type}"* ]] || return 1
  printf '%s' "${data}"
}

# lo::registry_tls_read <vol> — tls.crt and .sans from the volume into
# LO_REGISTRY_TLS_READ_CRT / LO_REGISTRY_TLS_READ_SANS. Returns 1 when the
# volume holds no complete pair (tls.crt must be a PEM CERTIFICATE, tls.key
# a PEM block; the key's bytes are checked and discarded, never kept; a
# half-populated or damaged volume counts as empty so the caller mints
# again), 2 when docker failed (the error line is already printed).
lo::registry_tls_read() {
  LO_REGISTRY_TLS_READ_CRT="" LO_REGISTRY_TLS_READ_SANS=""
  _lo_registry_tls_read_files() {
    local ctr="${1}" crt sans has_crt=0 has_key=0
    if crt=$(lo::registry_tls_volume_pem "${ctr}" tls.crt "CERTIFICATE"); then has_crt=1; fi
    if lo::registry_tls_volume_pem "${ctr}" tls.key >/dev/null; then has_key=1; fi
    sans=$(lo::registry_tls_volume_read "${ctr}" .sans) || sans=$'\001'
    (( has_crt && has_key )) || return 1
    LO_REGISTRY_TLS_READ_CRT="${crt%$'\001'}"
    LO_REGISTRY_TLS_READ_SANS="${sans%$'\001'}"
  }
  local rc=0
  lo::registry_tls_with_volume "${1}" _lo_registry_tls_read_files || rc=$?
  case "${rc}" in
    0) return 0 ;;
    1) return 1 ;;
    *) return 2 ;;
  esac
}

# lo::registry_tls_store <vol> <exists 0|1> <dir> [dereference 0|1] — copy
# the LO_REGISTRY_TLS_FILES present in dir into the volume, creating it first
# when exists is 0. dereference adds `docker cp -L` (the import: a symlinked
# file copies its target).
lo::registry_tls_store() {
  local vol="${1}" exists="${2}" dir="${3}" dereference="${4:-0}" err
  if (( ! exists )); then
    if ! err=$(docker volume create "${vol}" 2>&1 >/dev/null); then
      echo "error: docker volume create ${vol} failed: ${err%%$'\n'*}" >&2
      return 1
    fi
  fi
  _lo_registry_tls_populate() {
    local ctr="${1}" name src err
    local -a cp_args=(cp)
    (( dereference )) && cp_args+=(-L)
    for name in "${LO_REGISTRY_TLS_FILES[@]}"; do
      src="${dir}/${name}"
      [[ -f "${src}" ]] || continue
      if ! err=$(docker "${cp_args[@]}" "${src}" "${ctr}:${LO_REGISTRY_TLS_MOUNT}/${name}" 2>&1 >/dev/null); then
        echo "error: docker cp ${name} into volume ${vol} failed: ${err%%$'\n'*}" >&2
        return 1
      fi
    done
  }
  lo::registry_tls_with_volume "${vol}" _lo_registry_tls_populate
}

# lo::registry_tls_import <vol> — create the volume from the legacy
# ${PATH_BASE}/.secrets/tls/registries pair (a release before v0.4.0), byte
# for byte. The files stay: the running containers still bind-mount them until
# the operator recreates the set. Returns 2 when there is nothing to import.
lo::registry_tls_import() {
  local vol="${1}" legacy="${PATH_BASE}/.secrets/tls/registries"
  local has_crt=0 has_key=0
  [[ -f "${legacy}/tls.crt" ]] && has_crt=1
  [[ -f "${legacy}/tls.key" ]] && has_key=1
  (( has_crt || has_key )) || return 2
  if (( has_crt != has_key )); then
    # Half a pair is no pair: say so once, then mint fresh.
    warn "registry TLS: the legacy directory ${legacy} holds an incomplete pair (tls.crt or tls.key is missing). Minting a fresh certificate."
    return 2
  fi
  # -L: a symlinked legacy file copies its target, not the link.
  lo::registry_tls_store "${vol}" 0 "${legacy}" 1 || return 1
  warn "registry TLS cert imported from ${legacy} into volume ${vol}. The running registry containers still mount ${legacy}. Next: lo registry down && lo registry up"
}

# lo::registries_tls_cert <domain> — make sure the set's volume holds a cert
# for the current SAN set. No-op unless spec.registries.tls. Order: a missing
# volume is imported from the legacy directory when that holds a pair; an
# existing volume whose .sans equals the current SAN set is up to date;
# otherwise the plugin mints a fresh leaf into the volume.
lo::registries_tls_cert() {
  local domain_name="${1}"
  registry::is_tls || return 0

  local -a sans=()
  mapfile -t sans < <(lo::registry_tls_sans)
  if (( ${#sans[@]} == 0 )); then
    echo "error: no registry SANs resolved — cannot mint registry TLS cert" >&2
    return 1
  fi
  local vol
  vol=$(lo::registry_tls_volume)

  local exists=0 rc=0
  if lo::registry_tls_volume_exists "${vol}"; then
    exists=1
  else
    lo::registry_tls_import "${vol}" || rc=$?
    case "${rc}" in
      0) exists=1 ;;
      2) ;;
      *) return 1 ;;
    esac
  fi
  if (( exists )); then
    rc=0
    lo::registry_tls_read "${vol}" || rc=$?
    (( rc != 2 )) || return 1
    if (( rc == 0 )); then
      local prev="${LO_REGISTRY_TLS_READ_SANS}"
      while [[ "${prev}" == *$'\n' ]]; do prev="${prev%$'\n'}"; done
      if [[ "${prev}" == "$(printf '%s\n' "${sans[@]}")" ]]; then
        LO_REGISTRY_TLS_CRT="${LO_REGISTRY_TLS_READ_CRT}"
        debug "registry TLS cert up to date (${#sans[@]} SANs)"
        return 0
      fi
    fi
  fi
  lo::registry_tls_mint "${domain_name}" "${vol}" "${exists}" "${sans[@]}"
}

# lo::registry_tls_mint <domain> <vol> <exists 0|1> <san…> — drive the Secret
# plugin for the SAN set and store the result in the volume (created when
# exists is 0). The plugin gets a scratch PATH_SECRETS under the domain dir
# (its leaf cache and the extracted files), removed on every exit; never
# $TMPDIR, never a project store. Sets LO_REGISTRY_TLS_CRT.
lo::registry_tls_mint() {
  local domain_name="${1}" vol="${2}" exists="${3}"
  shift 3

  local plugin_bin="${KUSTOMIZE_PLUGIN_HOME:-${PATH_BASE}/.kustomize}/secrets.lok8s.dev/v1/secret/Secret"
  # The Secret plugin mints the cert. It's needed across the lok8s flow anyway, so
  # build it on demand if it's missing and we can (the `lo kustomize build` path is
  # in scope under `lo`); otherwise fail with guidance.
  if [[ ! -x "${plugin_bin}" ]] && declare -F kustomize::build >/dev/null; then
    debug "registry TLS: Secret plugin missing — building it (lo kustomize build)"
    kustomize::build || true
  fi
  if [[ ! -x "${plugin_bin}" ]]; then
    echo "error: spec.registries.tls is true (default) but the Secret plugin is not built at" >&2
    echo "       ${plugin_bin}. Build it with 'lo kustomize build' (needs go), or set" >&2
    echo "       spec.registries.tls: false for plain-HTTP registries. Then retry." >&2
    return 1
  fi

  local domain_dir="${PATH_CLUSTERS}/${domain_name}"
  mkdir -p "${domain_dir}"
  # A mint killed mid-way leaves its scratch (and the key in it) behind;
  # sweep every stale one before creating this run's.
  local -a stale=()
  local s
  for s in "${domain_dir}/${LO_REGISTRY_TLS_SCRATCH_PREFIX}"*; do
    [[ -d "${s}" ]] && stale+=("${s}")
  done
  if (( ${#stale[@]} )); then
    rm -rf "${stale[@]}"
    debug "registry TLS: removed ${#stale[@]} stale scratch dir(s) under ${domain_dir}"
  fi
  local scratch rc=0
  scratch=$(mktemp -d "${domain_dir}/${LO_REGISTRY_TLS_SCRATCH_PREFIX}XXXXXX") || return 1
  lo::registry_tls_mint_into "${scratch}" "${plugin_bin}" "${vol}" "${exists}" "$@" || rc=$?
  rm -rf "${scratch}"
  return "${rc}"
}

# The mint body, run with the scratch dir owned by lo::registry_tls_mint.
lo::registry_tls_mint_into() {
  local scratch="${1}" plugin_bin="${2}" vol="${3}" exists="${4}"
  shift 4
  local -a sans=("$@")

  # JSON array of SANs (jq guarantees valid quoting); YAML accepts it inline.
  local hosts_json
  hosts_json=$(printf '%s\n' "${sans[@]}" | jq -R . | jq -s -c .)

  local name="registries-tls" ns="lok8s-system"
  local manifest
  manifest=$(cat <<EOF
apiVersion: secrets.lok8s.dev/v1
kind: Secret
metadata:
  name: ${name}
  namespace: ${ns}
type: kubernetes.io/tls
cert:
  hosts: ${hosts_json}
EOF
)

  # The scratch store rides on the child's env only (never exported here).
  local out
  out=$(printf '%s\n' "${manifest}" | PATH_SECRETS="${scratch}" "${plugin_bin}") || {
    echo "error: the Secret plugin failed to mint the registry TLS cert" >&2
    return 1
  }

  local crt_b64 key_b64
  crt_b64=$(printf '%s\n' "${out}" | yq -r '.data["tls.crt"]')
  key_b64=$(printf '%s\n' "${out}" | yq -r '.data["tls.key"]')
  if [[ -z "${crt_b64}" || "${crt_b64}" == "null" || -z "${key_b64}" || "${key_b64}" == "null" ]]; then
    echo "error: registry TLS cert extraction failed (plugin output had no tls.crt/tls.key)" >&2
    return 1
  fi
  printf '%s' "${crt_b64}" | base64 -d > "${scratch}/tls.crt"
  (umask 077 && printf '%s' "${key_b64}" | base64 -d > "${scratch}/tls.key")
  printf '%s\n' "${sans[@]}" > "${scratch}/.sans"

  lo::registry_tls_store "${vol}" "${exists}" "${scratch}" || return 1
  local crt
  crt=$(cat "${scratch}/tls.crt"; printf '\001')
  LO_REGISTRY_TLS_CRT="${crt%$'\001'}"
  debug "minted registry TLS cert with SANs: ${sans[*]}"
}

# lo::registry_cert_mount <container> — what the container mounts at
# LO_REGISTRY_TLS_MOUNT: "volume|NAME", "bind|SOURCE", "none" (a container
# without the mount: plain mode) or "absent" (no such container). The same
# inspect template as the Go driver.
lo::registry_cert_mount() {
  local out
  if ! out=$(docker inspect -f '{{range .Mounts}}{{.Destination}}|{{.Type}}|{{.Name}}|{{.Source}}{{"\n"}}{{end}}' "${1}" 2>/dev/null); then
    echo absent
    return 0
  fi
  local dest type name src found=none
  while IFS='|' read -r dest type name src; do
    [[ "${dest}" == "${LO_REGISTRY_TLS_MOUNT}" ]] || continue
    if [[ "${type}" == "volume" ]]; then
      found="volume|${name}"
    else
      found="${type}|${src}"
    fi
  done <<<"${out}"
  echo "${found}"
}

# lo::registries_tls_nudge — warn (non-fatally) if registry TLS is on but the dev
# CA isn't trusted by this host yet. The cluster and in-cluster pulls work
# regardless (containerd trusts via the explicit certs.d CA file); only host
# `docker push` (the Tilt build loop) validates against the system trust store,
# so it fails until the CA is trusted. Detection is best-effort: `openssl verify`
# checks the same host store the Docker daemon uses.
lo::registries_tls_nudge() {
  registry::is_tls || return 0
  command -v openssl &>/dev/null || return 0   # can't check → stay quiet

  local caroot="${CAROOT:-${XDG_DATA_HOME:-${HOME}/.local/share}/mkcert}"
  local ca="${caroot}/rootCA.pem"
  if [[ -f "${ca}" ]] && openssl verify "${ca}" &>/dev/null; then
    return 0   # CA is in the host trust store → host pushes will verify
  fi

  warn "Registry TLS is on, but this machine doesn't trust the dev CA yet —"
  warn "  in-cluster pulls work, but 'docker push' to the build registry will fail."
  warn "  Fix it once:  lo trust   (or insecure-registries / a rootless runtime)"
  warn "  How: https://lok8s.io/guide/shared-registries#host-push-trust-options"
}

# lo::registry_ip_holder <network> <ip> — name of the container currently
# holding <ip> on <network>, empty if free. IPv4Address carries the /prefix,
# so match "<ip>/" as a prefix (never .2 matching .20).
lo::registry_ip_holder() {
  local network="${1}" ip="${2}"
  docker network inspect "${network}" \
    -f '{{range .Containers}}{{.IPv4Address}} {{.Name}}{{"\n"}}{{end}}' 2>/dev/null \
    | awk -v ip="${ip}/" 'index($1, ip) == 1 { print $2; exit }'
}

# lo::registries — reconcile every registry container to its desired state.
# Idempotent: a RUNNING container whose config-hash label matches is left
# alone; drift (config, image, address, TLS cert) or a dead container means
# recreate. Emits kubectl-style "registry/<name> <verb>" progress lines so
# callers can wrap it in kapply::run for the collapsing services-style UI.
# One registry failing does not abort the rest — errors are surfaced and the
# function returns non-zero at the end.
lo::registries() {
  local domain="${1}" cluster_yaml="${2}"
  local registry_config_dir="${PATH_LOK8S}/drivers/lo/cluster/registry"

  # In TLS mode every registry container mounts the set's cert volume
  # (lo::registries_tls_cert must run first — it does, in driver::provision).
  # The cert content feeds the config hash: registries read it once at startup,
  # so a re-minted cert (SAN change) must recreate the containers. The mount
  # SOURCE is not part of the hash: a container that still bind-mounts the
  # legacy directory is recreated by the operator (`lo registry down && lo
  # registry up`), not behind their back.
  local tls_mount_args=() cert_sig=""
  if registry::is_tls; then
    local vol
    vol=$(lo::registry_tls_volume)
    if [[ -z "${LO_REGISTRY_TLS_CRT}" ]]; then
      local read_rc=0
      lo::registry_tls_read "${vol}" || read_rc=$?
      (( read_rc != 2 )) || return 1
      if (( read_rc == 1 )); then
        echo "error: spec.registries.tls is true but volume ${vol} holds no complete tls.crt + tls.key pair. Next: lo up" >&2
        return 1
      fi
      LO_REGISTRY_TLS_CRT="${LO_REGISTRY_TLS_READ_CRT}"
    fi
    tls_mount_args=(--volume "${vol}:${LO_REGISTRY_TLS_MOUNT}:ro")
    cert_sig=$(printf '%s' "${LO_REGISTRY_TLS_CRT}" | sha256sum)
    cert_sig="${cert_sig%% *}"
  fi

  mkdir -p "${LO_REGISTRY_STATE_DIR}"

  local failed=0

  _lo_registry_start() {
    # reg_domain: keep the per-entry field from shadowing an inherited `domain`.
    local name="${1}" ip="${2}" url="${3}" reg_domain="${4}" host="${5}" type="${6}"
    local container_info
    container_info=$(registry::container "${name}")
    local reg_name="${container_info%%	*}"
    local reg_network="${container_info##*	}"

    local config_file="${registry_config_dir}/${name}.yaml"
    if [[ ! -f "${config_file}" ]] && [[ -n "${url}" ]]; then
      config_file="${registry_config_dir}/mirror.yaml"
    fi
    if [[ ! -f "${config_file}" ]]; then
      echo "error: registry/${reg_name}: no config for '${name}' at ${registry_config_dir}" >&2
      failed=1
      return 0
    fi

    # Render config for the active mode (TLS block swap + mirror URL).
    local rendered
    rendered=$(lo::render_registry_config "${config_file}" "${url}")

    # Desired-state hash. config_path is part of it: moving
    # LO_REGISTRY_STATE_DIR must recreate containers, or they'd keep a bind
    # to the abandoned path and the vanished-mount failure would return.
    local config_path="${LO_REGISTRY_STATE_DIR}/${reg_name}.yaml"
    local desired_hash
    desired_hash=$(printf '%s\n' "${rendered}" "${LO_REGISTRY_IMAGE}" "${reg_network}" "${ip}" "${config_path}" "${cert_sig}" | sha256sum)
    desired_hash="${desired_hash%% *}"

    # Serialize reconciliation of this registry across concurrent `lo` runs
    # (shared mirrors are host-global). Best-effort: without flock, two
    # simultaneous runs can race rm/run on the same container — the loser's
    # in-flight container may be removed, healed by the next run.
    local lockfd=0
    if command -v flock >/dev/null 2>&1 && exec 9>"${config_path}.lock"; then
      lockfd=1
      flock -w 60 9 || debug "registry ${reg_name}: lock wait timed out, proceeding unlocked"
    fi
    _lo_registry_reconcile "${reg_name}" "${reg_network}" "${ip}" \
      "${config_path}" "${rendered}" "${desired_hash}" || failed=1
    (( lockfd )) && exec 9>&-
    return 0
  }

  # The mutating half of the reconcile, run under the per-registry lock.
  # Inspects state INSIDE the lock so a concurrent run that just (re)created
  # the container is observed, not clobbered.
  _lo_registry_reconcile() {
    local reg_name="${1}" reg_network="${2}" ip="${3}"
    local config_path="${4}" rendered="${5}" desired_hash="${6}"

    local state current_hash
    state=$(docker inspect -f '{{.State.Status}}' "${reg_name}" 2>/dev/null || echo absent)
    current_hash=$(docker inspect -f '{{index .Config.Labels "lok8s.dev/config-hash"}}' "${reg_name}" 2>/dev/null || true)

    if [[ "${state}" == "running" && "${current_hash}" == "${desired_hash}" ]]; then
      echo "registry/${reg_name} unchanged"
      return 0
    fi

    local verb
    case "${state}" in
      absent)  verb="created" ;;
      running) verb="configured" ;;   # up, but config/image/cert drifted
      *)       verb="restarted" ;;    # created/exited/dead — recreate
    esac

    # Durable config path — the daemon re-binds it on every container restart
    # (see LO_REGISTRY_STATE_DIR in defaults.sh). Guarded: a failed write
    # (read-only dir, disk full) must not proceed to remove a healthy
    # container that would then restart against a stale or missing config.
    if ! printf '%s\n' "${rendered}" > "${config_path}"; then
      echo "error: registry/${reg_name}: cannot write config at ${config_path}" >&2
      return 1
    fi

    docker volume create "${reg_name}" >/dev/null 2>&1 || true
    docker rm -f "${reg_name}" >/dev/null 2>&1 || true

    local attempt run_err=""
    for attempt in 1 2; do
      if run_err=$(docker run -d --restart=always --name "${reg_name}" \
        --label "lok8s.dev/config-hash=${desired_hash}" \
        --volume "${reg_name}:/var/lib/registry" \
        --volume "${config_path}:/config.yaml:ro" \
        "${tls_mount_args[@]}" \
        --net="${reg_network}" --ip "${ip}" \
        "${LO_REGISTRY_IMAGE}" "/config.yaml" 2>&1 >/dev/null); then
        echo "registry/${reg_name} ${verb}"
        return 0
      fi
      # Lost a race with a concurrent `lo` run despite best-effort locking:
      # the other run winning IS the desired state.
      if [[ "$(docker inspect -f '{{.State.Status}}' "${reg_name}" 2>/dev/null)" == "running" ]]; then
        echo "registry/${reg_name} unchanged"
        return 0
      fi
      # Don't leave a half-created container behind — `docker run` creates it
      # even when the start fails, and a stuck-Created container shadows the
      # name on the next attempt.
      docker rm -f "${reg_name}" >/dev/null 2>&1 || true
      (( attempt == 1 )) || break
      # One bounded retry for a transiently-held address: the endpoint of the
      # container we just removed can lag its release. A PERSISTENT holder
      # should be impossible on a range-reserved network (lo::registry_network
      # recreates legacy ones) — if one appears anyway, fail loudly with the
      # holder named rather than shuffling someone else's container.
      local holder
      if [[ "${run_err,,}" == *"address already in use"* ]]; then
        holder=$(lo::registry_ip_holder "${reg_network}" "${ip}")
        if [[ -n "${holder}" ]]; then
          echo "error: registry/${reg_name}: ${ip} is held by '${holder}' on '${reg_network}'." >&2
          if [[ "${reg_network}" == "$(registry::network_name)" ]]; then
            # Shared net: recreating it (which reserves the dynamic range) is
            # always the fix — clean detaches any holder.
            echo "error: recreate the shared network: lo registry clean --shared && lo up" >&2
          else
            # Project net (legacy, created before its reserved range): the
            # holder is almost always a kind node that grabbed the address
            # after a host reboot. Detaching a live node changes its address
            # (lo up heals the node-ip afterwards); recreating the cluster
            # rebuilds the network WITH the range.
            echo "error: a kind node likely grabbed this address after a reboot — run: docker network disconnect -f ${reg_network} ${holder} && lo up" >&2
            echo "error: (or recreate the cluster — 'lo down && lo up' — to rebuild '${reg_network}' with its reserved dynamic range)" >&2
          fi
          return 1
        fi
        sleep 1
      else
        break
      fi
    done

    echo "error: registry/${reg_name}: ${run_err}" >&2
    return 1
  }

  registry::each _lo_registry_start

  (( failed == 0 ))
}

lo::apply_local_registry_hosting() {
  local domain="${1}"
  local cluster_yaml="${PATH_CLUSTERS}/${domain}/cluster.lok8s.yaml"
  local cluster_name
  cluster_name=$(yq -r '.metadata.name' "${cluster_yaml}" 2>/dev/null)
  local kubeconfig="${PATH_BASE}/.kubeconfig/${cluster_name}.yaml"
  [[ -f "${kubeconfig}" ]] || { echo "warning: no kubeconfig at ${kubeconfig}, skipping local-registry-hosting" >&2; return 0; }

  local build_ip build_host
  build_ip=$(registry::get build ip)
  build_host=$(registry::get build host)
  [[ -n "${build_ip}" ]] || { echo "warning: build registry IP unknown, skipping local-registry-hosting" >&2; return 0; }
  [[ -n "${build_host}" ]] || build_host="lok8s.local"

  kubectl apply --kubeconfig "${kubeconfig}" -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
  namespace: kube-public
  labels:
    lok8s.dev/type: system
data:
  localRegistryHosting.v1: |
    host: "${build_ip}"
    hostFromClusterNetwork: "${build_host}"
    help: "https://kernpilot.github.io/lok8s/guide/services#how-the-image-swap-actually-works"
EOF
}

lo::cleanup_registries() {
  local cluster_name="${1}"

  _lo_registry_cleanup() {
    # reg_domain: keep the per-entry field from shadowing an inherited `domain`.
    local name="${1}" ip="${2}" url="${3}" reg_domain="${4}" host="${5}" type="${6}"
    # Skip shared mirrors — they persist across project lifecycles
    if registry::is_shared && [[ "${type}" == "mirror" ]]; then
      return 0
    fi
    local container_info
    container_info=$(registry::container "${name}")
    local reg_name="${container_info%%	*}"
    docker rm -f "${reg_name}" 2>/dev/null || true
    docker volume rm -f "${reg_name}" 2>/dev/null || true
    rm -f "${LO_REGISTRY_STATE_DIR}/${reg_name}.yaml" "${LO_REGISTRY_STATE_DIR}/${reg_name}.yaml.lock"
  }

  registry::each _lo_registry_cleanup

  # The set's cert volume goes with its data volumes (re-minted by the next
  # `lo up`). docker refuses while a shared mirror still mounts it; that
  # mirror keeps serving the cert until `lo registry clean --shared`.
  if registry::is_tls; then
    docker volume rm -f "$(lo::registry_tls_volume)" 2>/dev/null || true
    LO_REGISTRY_TLS_CRT=""
  fi
}

lo::registry_configmap() {
  local domain="${1}" cluster_yaml="${2}"
  local cluster_name
  cluster_name=$(yq -r '.metadata.name' "${cluster_yaml}")
  local kubeconfig="${PATH_BASE}/.kubeconfig/${cluster_name}.yaml"
  local json="${LOK8S_REGISTRY_JSON}"

  # Build ConfigMap data from JSON in a single jq call
  local configmap_data
  configmap_data=$(jq -r '
    .registries[] |
    "  " + .name + ".ip: \"" + .ip + "\"\n" +
    "  " + .name + ".port: \"5000\"\n" +
    (if .url != "" then "  " + .name + ".url: \"" + .url + "\"\n" else "" end) +
    (if .type == "mirror" then "  " + .name + ".shared: \"true\"\n" else "" end)
  ' "${json}")

  kubectl apply --kubeconfig "${kubeconfig}" -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: lok8s-registries
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: lok8s
data:
${configmap_data}
EOF
}
