# shellcheck shell=bash disable=SC2034
# registries.sh — Registry container lifecycle
# Reads from .registries.json (generated by config-registry.sh)

# lo::registry_http_block — emit the registry `http:` stanza for the
# active mode. The static config YAMLs ship the plain-HTTP block (:80);
# in TLS mode we replace it with a :443 listener referencing the
# mkcert cert+key mounted at LO_REGISTRY_TLS_MOUNT. Indentation matches
# the top-level `http:` key in the registry config (two-space children).
lo::registry_http_block() {
  if registry::is_tls; then
    cat <<EOF
http:
  addr: :${LO_REGISTRY_PORT_TLS}
  tls:
    certificate: ${LO_REGISTRY_TLS_MOUNT}/tls.crt
    key: ${LO_REGISTRY_TLS_MOUNT}/tls.key
  headers:
    X-Content-Type-Options: [nosniff]
EOF
  else
    cat <<EOF
http:
  addr: :${LO_REGISTRY_PORT}
  headers:
    X-Content-Type-Options: [nosniff]
EOF
  fi
}

# lo::render_registry_config — render a registry config file for the
# active mode. Substitutes ${REMOTE_URL} for mirrors and swaps the
# http: block to TLS when enabled. Reads the static file, strips its
# hardcoded http: stanza (the `http:` line plus its indented children),
# and appends the mode-appropriate block.
lo::render_registry_config() {
  local config_file="$1" url="$2"

  local base
  if [[ -n "${url}" ]]; then
    base=$(REMOTE_URL="${url}" envsubst '${REMOTE_URL}' < "${config_file}")
  else
    base=$(cat "${config_file}")
  fi

  # Drop the existing http: block (top-level key + its 2-space-indented
  # body) so we can re-emit it for the active mode. awk: when we hit a
  # line starting exactly `http:`, skip it and all following lines that
  # are indented (children) until the next top-level key.
  local without_http
  without_http=$(echo "${base}" | awk '
    /^http:/ { skip = 1; next }
    skip && /^[[:space:]]/ { next }
    { skip = 0; print }
  ')

  printf '%s\n%s\n' "${without_http}" "$(lo::registry_http_block)"
}

lo::registries() {
  local domain="$1" cluster_yaml="$2"
  local registry_config_dir="${PATH_LOK8S}/drivers/lo/cluster/registry"

  # In TLS mode every registry container mounts the shared mkcert cert.
  local tls_mount_args=()
  if registry::is_tls; then
    local cert_dir="${PATH_BASE}/.secrets/tls/registries"
    if [[ ! -f "${cert_dir}/tls.crt" ]] || [[ ! -f "${cert_dir}/tls.key" ]]; then
      echo "error: registry TLS enabled but cert missing at ${cert_dir}" >&2
      echo "       lo::mkcert_registries must run before lo::registries." >&2
      return 1
    fi
    tls_mount_args=(--volume "${cert_dir}:${LO_REGISTRY_TLS_MOUNT}:ro")
  fi

  _lo_registry_start() {
    local name="$1" ip="$2" url="$3" domain="$4" host="$5" type="$6"
    local container_info
    container_info=$(registry::container "${name}")
    local reg_name="${container_info%%	*}"
    local reg_network="${container_info##*	}"

    local running
    running=$(docker inspect -f '{{.State.Running}}' "${reg_name}" 2>/dev/null || true)
    [[ "${running}" != "true" ]] || return 0

    docker volume create "${reg_name}" 2>/dev/null || true
    docker rm -f "${reg_name}" 2>/dev/null || true

    local config_file="${registry_config_dir}/${name}.yaml"
    if [[ ! -f "${config_file}" ]] && [[ -n "${url}" ]]; then
      config_file="${registry_config_dir}/mirror.yaml"
    fi
    if [[ ! -f "${config_file}" ]]; then
      echo "error: no registry config for '${name}' at ${registry_config_dir}" >&2
      return 1
    fi

    # Render config for the active mode (TLS block swap + mirror URL).
    local tmp_config
    tmp_config=$(mktemp)
    lo::render_registry_config "${config_file}" "${url}" > "${tmp_config}"

    docker run -d --restart=always --name "${reg_name}" \
      --volume "${reg_name}:/var/lib/registry" \
      --volume "${tmp_config}:/config.yaml:ro" \
      "${tls_mount_args[@]}" \
      --net="${reg_network}" --ip "${ip}" \
      "${LO_REGISTRY_IMAGE}" "/config.yaml"

    rm -f "${tmp_config}"
  }

  registry::each _lo_registry_start
}

lo::apply_local_registry_hosting() {
  local domain="$1"
  local cluster_yaml="${PATH_CLUSTERS}/${domain}/cluster.lok8s.yaml"
  local cluster_name
  cluster_name=$(yq -r '.metadata.name' "${cluster_yaml}" 2>/dev/null)
  local kubeconfig="${PATH_BASE}/.kubeconfig/${cluster_name}.yaml"
  [[ -f "${kubeconfig}" ]] || { echo "warning: no kubeconfig at ${kubeconfig}, skipping local-registry-hosting" >&2; return 0; }

  local build_ip build_host
  build_ip=$(registry::get build ip)
  build_host=$(registry::get build host)
  [[ -n "${build_ip}" ]] || { echo "warning: build registry IP unknown, skipping local-registry-hosting" >&2; return 0; }
  [[ -n "${build_host}" ]] || build_host="lok8s.local"

  kubectl apply --kubeconfig "${kubeconfig}" -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
  namespace: kube-public
  labels:
    lok8s.dev/type: system
data:
  localRegistryHosting.v1: |
    host: "${build_ip}"
    hostFromClusterNetwork: "${build_host}"
    help: "https://kernpilot.github.io/lok8s/guide/services#how-the-image-swap-actually-works"
EOF
}

lo::cleanup_registries() {
  local cluster_name="$1"

  _lo_registry_cleanup() {
    local name="$1" ip="$2" url="$3" domain="$4" host="$5" type="$6"
    # Skip shared mirrors — they persist across project lifecycles
    if registry::is_shared && [[ "${type}" == "mirror" ]]; then
      return 0
    fi
    local container_info
    container_info=$(registry::container "${name}")
    local reg_name="${container_info%%	*}"
    docker rm -f "${reg_name}" 2>/dev/null || true
    docker volume rm -f "${reg_name}" 2>/dev/null || true
  }

  registry::each _lo_registry_cleanup
}

lo::registry_configmap() {
  local domain="$1" cluster_yaml="$2"
  local cluster_name
  cluster_name=$(yq -r '.metadata.name' "${cluster_yaml}")
  local kubeconfig="${PATH_BASE}/.kubeconfig/${cluster_name}.yaml"
  local json="${LOK8S_REGISTRY_JSON}"

  # Build ConfigMap data from JSON in a single jq call
  local configmap_data
  configmap_data=$(jq -r '
    .registries[] |
    "  " + .name + ".ip: \"" + .ip + "\"\n" +
    "  " + .name + ".port: \"5000\"\n" +
    (if .url != "" then "  " + .name + ".url: \"" + .url + "\"\n" else "" end) +
    (if .type == "mirror" then "  " + .name + ".shared: \"true\"\n" else "" end)
  ' "${json}")

  kubectl apply --kubeconfig "${kubeconfig}" -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: lok8s-registries
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: lok8s
data:
${configmap_data}
EOF
}
