# shellcheck shell=bash disable=SC2034
# registries.sh — Registry container lifecycle
# Reads from .registries.json (generated by config-registry.sh)

# lo::registry_http_block — emit the registry `http:` stanza for the
# active mode. The static config YAMLs ship the plain-HTTP block (:80);
# in TLS mode we replace it with a :443 listener referencing the
# mkcert cert+key mounted at LO_REGISTRY_TLS_MOUNT. Indentation matches
# the top-level `http:` key in the registry config (two-space children).
lo::registry_http_block() {
  if registry::is_tls; then
    cat <<EOF
http:
  addr: :${LO_REGISTRY_PORT_TLS}
  tls:
    certificate: ${LO_REGISTRY_TLS_MOUNT}/tls.crt
    key: ${LO_REGISTRY_TLS_MOUNT}/tls.key
  headers:
    X-Content-Type-Options: [nosniff]
EOF
  else
    cat <<EOF
http:
  addr: :${LO_REGISTRY_PORT}
  headers:
    X-Content-Type-Options: [nosniff]
EOF
  fi
}

# lo::render_registry_config — render a registry config file for the
# active mode. Substitutes ${REMOTE_URL} for mirrors and swaps the
# http: block to TLS when enabled. Reads the static file, strips its
# hardcoded http: stanza (the `http:` line plus its indented children),
# and appends the mode-appropriate block.
lo::render_registry_config() {
  local config_file="$1" url="$2"

  local base
  if [[ -n "${url}" ]]; then
    base=$(REMOTE_URL="${url}" envsubst '${REMOTE_URL}' < "${config_file}")
  else
    base=$(cat "${config_file}")
  fi

  # Drop the existing http: block (top-level key + its 2-space-indented
  # body) so we can re-emit it for the active mode. awk: when we hit a
  # line starting exactly `http:`, skip it and all following lines that
  # are indented (children) until the next top-level key.
  local without_http
  without_http=$(echo "${base}" | awk '
    /^http:/ { skip = 1; next }
    skip && /^[[:space:]]/ { next }
    { skip = 0; print }
  ')

  printf '%s\n%s\n' "${without_http}" "$(lo::registry_http_block)"
}

# lo::registries_tls_cert — mint the TLS cert the registries serve in TLS mode by
# driving the secrets.lok8s.dev Secret plugin (the binary lok8s already ships and
# requires — no mkcert/certgen). The cert is a `cert:` leaf whose SANs are built
# from .registries.json so it covers every registry IP plus the framework
# hostnames; the plugin signs it with the shared dev CA at CAROOT (created on
# demand) and we extract tls.crt/tls.key to .secrets/tls/registries/ for the
# container mounts.
#
# A separate cert from any application wildcard because the SAN list is
# registry-derived and has its own lifecycle. Idempotent: re-minted only when
# missing or when the SAN set changed (IPs shifted, a mirror added/removed). The
# host Docker client + containerd trust it once `lo trust` (mkcert -install) has
# installed the CA.
lo::registries_tls_cert() {
  registry::is_tls || return 0

  local plugin_bin="${KUSTOMIZE_PLUGIN_HOME:-${PATH_BASE}/.kustomize}/secrets.lok8s.dev/v1/secret/Secret"
  # The Secret plugin mints the cert. It's needed across the lok8s flow anyway, so
  # build it on demand if it's missing and we can (the `lo kustomize build` path is
  # in scope under `lo`); otherwise fail with guidance.
  if [[ ! -x "${plugin_bin}" ]] && declare -F kustomize::build >/dev/null; then
    debug "registry TLS: Secret plugin missing — building it (lo kustomize build)"
    kustomize::build || true
  fi
  if [[ ! -x "${plugin_bin}" ]]; then
    echo "error: spec.registries.tls is true (default) but the Secret plugin is not built at" >&2
    echo "       ${plugin_bin}. Build it with 'lo kustomize build' (needs go), or set" >&2
    echo "       spec.registries.tls: false for plain-HTTP registries. Then retry." >&2
    return 1
  fi
  if [[ -z "${PATH_SECRETS:-}" ]]; then
    echo "error: PATH_SECRETS is not set — cannot mint the registry TLS cert" >&2
    return 1
  fi

  local tls_dir="${PATH_BASE}/.secrets/tls/registries"
  local crt="${tls_dir}/tls.crt"
  local key="${tls_dir}/tls.key"
  local sans_file="${tls_dir}/.sans"
  mkdir -p "${tls_dir}"

  # Build the SAN list (hostnames first, then IPs) from the registry JSON.
  # Framework registries contribute their canonical hostname; mirrors contribute
  # the upstream domain they impersonate. Every registry contributes its IP.
  local -a sans=()
  _lo_registry_san() {
    local name="$1" ip="$2" url="$3" reg_domain="$4" host="$5" type="$6"
    [[ -n "${host}" ]] && sans+=("${host}")
    [[ -n "${reg_domain}" ]] && sans+=("${reg_domain}")
    [[ -n "${ip}" ]] && sans+=("${ip}")
  }
  registry::each _lo_registry_san

  if (( ${#sans[@]} == 0 )); then
    echo "error: no registry SANs resolved — cannot mint registry TLS cert" >&2
    return 1
  fi

  # Deduplicate while preserving order.
  local -A seen=()
  local -a uniq_sans=()
  local s
  for s in "${sans[@]}"; do
    [[ -n "${seen[${s}]:-}" ]] && continue
    seen[${s}]=1
    uniq_sans+=("${s}")
  done

  # Up to date? (cert present and the SAN set unchanged since the last mint)
  local sans_repr
  sans_repr=$(printf '%s\n' "${uniq_sans[@]}")
  if [[ -f "${crt}" && -f "${key}" && -f "${sans_file}" ]] \
    && [[ "$(cat "${sans_file}")" == "${sans_repr}" ]]; then
    debug "registry TLS cert up to date (${#uniq_sans[@]} SANs)"
    return 0
  fi

  # (Re)mint. The cert: generator caches its leaf by Secret name, so drop any
  # stale cache entry first to force a fresh signature for the new SAN set.
  local name="registries-tls" ns="lok8s-system"
  rm -f "${PATH_SECRETS}/Secret.${name}.${ns}.tls.crt" \
        "${PATH_SECRETS}/Secret.${name}.${ns}.tls.key"

  # JSON array of SANs (jq guarantees valid quoting); YAML accepts it inline.
  local hosts_json
  hosts_json=$(printf '%s\n' "${uniq_sans[@]}" | jq -R . | jq -s -c .)

  local manifest
  manifest=$(cat <<EOF
apiVersion: secrets.lok8s.dev/v1
kind: Secret
metadata:
  name: ${name}
  namespace: ${ns}
type: kubernetes.io/tls
cert:
  hosts: ${hosts_json}
EOF
)

  local out
  out=$(printf '%s\n' "${manifest}" | "${plugin_bin}") || {
    echo "error: the Secret plugin failed to mint the registry TLS cert" >&2
    return 1
  }

  local crt_b64 key_b64
  crt_b64=$(printf '%s\n' "${out}" | yq -r '.data["tls.crt"]')
  key_b64=$(printf '%s\n' "${out}" | yq -r '.data["tls.key"]')
  if [[ -z "${crt_b64}" || "${crt_b64}" == "null" || -z "${key_b64}" || "${key_b64}" == "null" ]]; then
    echo "error: registry TLS cert extraction failed (plugin output had no tls.crt/tls.key)" >&2
    return 1
  fi
  printf '%s' "${crt_b64}" | base64 -d > "${crt}"
  printf '%s' "${key_b64}" | base64 -d > "${key}"
  printf '%s\n' "${sans_repr}" > "${sans_file}"
  debug "minted registry TLS cert with SANs: ${uniq_sans[*]}"
}

# lo::registries_tls_nudge — warn (non-fatally) if registry TLS is on but the dev
# CA isn't trusted by this host yet. The cluster and in-cluster pulls work
# regardless (containerd trusts via the explicit certs.d CA file); only host
# `docker push` (the Tilt build loop) validates against the system trust store,
# so it fails until the CA is trusted. Detection is best-effort: `openssl verify`
# checks the same host store the Docker daemon uses.
lo::registries_tls_nudge() {
  registry::is_tls || return 0
  command -v openssl &>/dev/null || return 0   # can't check → stay quiet

  local caroot="${CAROOT:-${XDG_DATA_HOME:-${HOME}/.local/share}/mkcert}"
  local ca="${caroot}/rootCA.pem"
  if [[ -f "${ca}" ]] && openssl verify "${ca}" &>/dev/null; then
    return 0   # CA is in the host trust store → host pushes will verify
  fi

  warn "Registry TLS is on, but this machine doesn't trust the dev CA yet —"
  warn "  in-cluster pulls work, but 'docker push' to the build registry will fail."
  warn "  Fix it once:  lo trust   (or insecure-registries / a rootless runtime)"
  warn "  How: https://lok8s.io/guide/shared-registries#host-push-trust-options"
}

lo::registries() {
  local domain="$1" cluster_yaml="$2"
  local registry_config_dir="${PATH_LOK8S}/drivers/lo/cluster/registry"

  # In TLS mode every registry container mounts the shared cert minted by
  # lo::registries_tls_cert (which must run first — it does, in driver::provision).
  local tls_mount_args=()
  if registry::is_tls; then
    local cert_dir="${PATH_BASE}/.secrets/tls/registries"
    if [[ ! -f "${cert_dir}/tls.crt" ]] || [[ ! -f "${cert_dir}/tls.key" ]]; then
      echo "error: spec.registries.tls is enabled but no cert at ${cert_dir}" >&2
      echo "       lo::registries_tls_cert must run before lo::registries (ensure the" >&2
      echo "       Secret plugin is built: lo kustomize build)." >&2
      return 1
    fi
    tls_mount_args=(--volume "${cert_dir}:${LO_REGISTRY_TLS_MOUNT}:ro")
  fi

  _lo_registry_start() {
    local name="$1" ip="$2" url="$3" domain="$4" host="$5" type="$6"
    local container_info
    container_info=$(registry::container "${name}")
    local reg_name="${container_info%%	*}"
    local reg_network="${container_info##*	}"

    local running
    running=$(docker inspect -f '{{.State.Running}}' "${reg_name}" 2>/dev/null || true)
    [[ "${running}" != "true" ]] || return 0

    docker volume create "${reg_name}" 2>/dev/null || true
    docker rm -f "${reg_name}" 2>/dev/null || true

    local config_file="${registry_config_dir}/${name}.yaml"
    if [[ ! -f "${config_file}" ]] && [[ -n "${url}" ]]; then
      config_file="${registry_config_dir}/mirror.yaml"
    fi
    if [[ ! -f "${config_file}" ]]; then
      echo "error: no registry config for '${name}' at ${registry_config_dir}" >&2
      return 1
    fi

    # Render config for the active mode (TLS block swap + mirror URL).
    local tmp_config
    tmp_config=$(mktemp)
    lo::render_registry_config "${config_file}" "${url}" > "${tmp_config}"

    docker run -d --restart=always --name "${reg_name}" \
      --volume "${reg_name}:/var/lib/registry" \
      --volume "${tmp_config}:/config.yaml:ro" \
      "${tls_mount_args[@]}" \
      --net="${reg_network}" --ip "${ip}" \
      "${LO_REGISTRY_IMAGE}" "/config.yaml"

    rm -f "${tmp_config}"
  }

  registry::each _lo_registry_start
}

lo::apply_local_registry_hosting() {
  local domain="$1"
  local cluster_yaml="${PATH_CLUSTERS}/${domain}/cluster.lok8s.yaml"
  local cluster_name
  cluster_name=$(yq -r '.metadata.name' "${cluster_yaml}" 2>/dev/null)
  local kubeconfig="${PATH_BASE}/.kubeconfig/${cluster_name}.yaml"
  [[ -f "${kubeconfig}" ]] || { echo "warning: no kubeconfig at ${kubeconfig}, skipping local-registry-hosting" >&2; return 0; }

  local build_ip build_host
  build_ip=$(registry::get build ip)
  build_host=$(registry::get build host)
  [[ -n "${build_ip}" ]] || { echo "warning: build registry IP unknown, skipping local-registry-hosting" >&2; return 0; }
  [[ -n "${build_host}" ]] || build_host="lok8s.local"

  kubectl apply --kubeconfig "${kubeconfig}" -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
  namespace: kube-public
  labels:
    lok8s.dev/type: system
data:
  localRegistryHosting.v1: |
    host: "${build_ip}"
    hostFromClusterNetwork: "${build_host}"
    help: "https://kernpilot.github.io/lok8s/guide/services#how-the-image-swap-actually-works"
EOF
}

lo::cleanup_registries() {
  local cluster_name="$1"

  _lo_registry_cleanup() {
    local name="$1" ip="$2" url="$3" domain="$4" host="$5" type="$6"
    # Skip shared mirrors — they persist across project lifecycles
    if registry::is_shared && [[ "${type}" == "mirror" ]]; then
      return 0
    fi
    local container_info
    container_info=$(registry::container "${name}")
    local reg_name="${container_info%%	*}"
    docker rm -f "${reg_name}" 2>/dev/null || true
    docker volume rm -f "${reg_name}" 2>/dev/null || true
  }

  registry::each _lo_registry_cleanup
}

lo::registry_configmap() {
  local domain="$1" cluster_yaml="$2"
  local cluster_name
  cluster_name=$(yq -r '.metadata.name' "${cluster_yaml}")
  local kubeconfig="${PATH_BASE}/.kubeconfig/${cluster_name}.yaml"
  local json="${LOK8S_REGISTRY_JSON}"

  # Build ConfigMap data from JSON in a single jq call
  local configmap_data
  configmap_data=$(jq -r '
    .registries[] |
    "  " + .name + ".ip: \"" + .ip + "\"\n" +
    "  " + .name + ".port: \"5000\"\n" +
    (if .url != "" then "  " + .name + ".url: \"" + .url + "\"\n" else "" end) +
    (if .type == "mirror" then "  " + .name + ".shared: \"true\"\n" else "" end)
  ' "${json}")

  kubectl apply --kubeconfig "${kubeconfig}" -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: lok8s-registries
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: lok8s
data:
${configmap_data}
EOF
}
