package cli

// cmd_crds_test.go covers `lo crds` generate and check.

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/kernpilot/lok8s/internal/config"
	"github.com/kernpilot/lok8s/internal/testutil"
)

func crdsSandbox(t *testing.T) *config.Paths {
	t.Helper()
	repo := repoRootDir(t)
	p := synthProject(t)
	schemas, _ := filepath.Glob(filepath.Join(repo, "operator", "crds", "schema", "*.schema.yaml"))
	if len(schemas) == 0 {
		t.Skip("no schema source")
	}
	for _, s := range schemas {
		raw, _ := os.ReadFile(s)
		testutil.WriteFile(t, filepath.Join(p.Base, "operator", "crds", "schema", filepath.Base(s)), string(raw))
	}
	return p
}

func TestCrdsGenerateThenCheck(t *testing.T) {
	p := crdsSandbox(t)
	stdout, _, err := runLo(t, NewRoot(p), "crds", "generate")
	if err != nil {
		t.Fatal(err)
	}
	for _, kind := range []string{"lo", "capi", "kkp", "kubeone", "deploy", "clusterinventory"} {
		if _, err := os.Stat(filepath.Join(p.Base, "operator", "crds", kind+".yaml")); err != nil {
			t.Errorf("generate skipped %s", kind)
		}
		if !strings.Contains(stdout, "  wrote operator/crds/"+kind+".yaml\n") {
			t.Errorf("no progress line for %s:\n%s", kind, stdout)
		}
	}
	mirror := filepath.Join(p.Lok8s, "libs", "inventory", "manifests", "clusterinventory.crd.yaml")
	if _, err := os.Stat(mirror); err != nil {
		t.Error("inventory mirror not written")
	}
	if !strings.Contains(stdout, "  wrote .lok8s/libs/inventory/manifests/clusterinventory.crd.yaml (mirror for synced .lok8s trees)\n") {
		t.Errorf("mirror progress line:\n%s", stdout)
	}
	head, _ := os.ReadFile(filepath.Join(p.Base, "operator", "crds", "lo.yaml"))
	if !strings.HasPrefix(string(head), "# GENERATED by 'lo crds generate'") {
		t.Error("banner missing")
	}

	stdout, _, err = runLo(t, NewRoot(p), "crds", "check")
	if err != nil || stdout != "  all CRDs up to date.\n" {
		t.Errorf("check after generate: err=%v stdout=%q", err, stdout)
	}
	_, _, err = runLo(t, NewRoot(p), "crds", "c")
	if err != nil {
		t.Errorf("alias c: %v", err)
	}
}

// The drift gate: a hand edit to a generated CRD (or the mirror) must fail
// `lo crds check`.
func TestCrdsCheckDetectsDrift(t *testing.T) {
	p := crdsSandbox(t)
	if _, _, err := runLo(t, NewRoot(p), "crds", "generate"); err != nil {
		t.Fatal(err)
	}
	appendTo := func(path string) {
		f, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0o644)
		if err != nil {
			t.Fatal(err)
		}
		f.WriteString("  hand-edited: true\n")
		f.Close()
	}
	appendTo(filepath.Join(p.Base, "operator", "crds", "lo.yaml"))
	_, stderr, err := runLo(t, NewRoot(p), "crds", "check")
	if !errors.Is(err, ErrHandled) || !strings.Contains(stderr, "operator/crds/lo.yaml is STALE") {
		t.Errorf("drift not detected: err=%v stderr=%q", err, stderr)
	}

	if _, _, err := runLo(t, NewRoot(p), "crds", "generate"); err != nil {
		t.Fatal(err)
	}
	appendTo(filepath.Join(p.Lok8s, "libs", "inventory", "manifests", "clusterinventory.crd.yaml"))
	_, stderr, err = runLo(t, NewRoot(p), "crds", "check")
	if !errors.Is(err, ErrHandled) || !strings.Contains(stderr, ".lok8s/libs/inventory/manifests/clusterinventory.crd.yaml is STALE") {
		t.Errorf("mirror drift not detected: err=%v stderr=%q", err, stderr)
	}

	_, stderr, err = runLo(t, NewRoot(p), "crds", "bogus")
	if !errors.Is(err, ErrHandled) || !strings.Contains(stderr, "Invalid command: bogus") {
		t.Errorf("crds bogus: err=%v stderr=%q", err, stderr)
	}
}
