package lo

// registries.go — registry container lifecycle
// (.lok8s/drivers/lo/utils/registries.sh). Reads from .registries.json
// (generated by configregistry.go).

import (
	"context"
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/kernpilot/lok8s/internal/execx"
	"github.com/kernpilot/lok8s/internal/ui"
)

// registryHTTPBlock emits the registry `http:` stanza for the active mode
// (bash: lo::registry_http_block). The static config YAMLs ship the
// plain-HTTP block (:80); in TLS mode it is replaced with a :443 listener
// referencing the cert+key mounted at RegistryTLSMount.
func registryHTTPBlock(tls bool) string {
	if tls {
		return fmt.Sprintf(`http:
  addr: :%d
  tls:
    certificate: %s/tls.crt
    key: %s/tls.key
  headers:
    X-Content-Type-Options: [nosniff]`, RegistryPortTLS, RegistryTLSMount, RegistryTLSMount)
	}
	return fmt.Sprintf(`http:
  addr: :%d
  headers:
    X-Content-Type-Options: [nosniff]`, RegistryPort)
}

// renderRegistryConfig renders a registry config file for the active mode
// (bash: lo::render_registry_config): substitutes ${REMOTE_URL} for mirrors
// and swaps the http: block to TLS when enabled. Pure-Go placeholder
// substitution — the bash deliberately did NOT shell out to envsubst (the
// b-managed Go envsubst rejects gettext's SHELL-FORMAT positional argument,
// silently emptying the config), and neither does this.
func renderRegistryConfig(configFile, url string, tls bool) (string, error) {
	raw, err := os.ReadFile(configFile)
	if err != nil {
		return "", err
	}
	base := string(raw)
	if url != "" {
		base = strings.ReplaceAll(base, "${REMOTE_URL}", url)
	}

	// Drop the existing http: block (top-level key + its indented body) so
	// the mode-appropriate block can be re-emitted. Same awk semantics: when
	// a line starts exactly `http:`, skip it and all following indented
	// (child) lines until the next top-level key.
	var kept []string
	skip := false
	for _, line := range strings.Split(base, "\n") {
		if strings.HasPrefix(line, "http:") {
			skip = true
			continue
		}
		if skip && line != "" && (line[0] == ' ' || line[0] == '\t') {
			continue
		}
		skip = false
		kept = append(kept, line)
	}
	// The bash call sites capture with $(…), which strips the trailing
	// newline — the returned string therefore ends at the http block's last
	// line, and writers re-append the "\n" (printf '%s\n'), exactly like the
	// bash `rendered` variable.
	withoutHTTP := strings.TrimRight(strings.Join(kept, "\n"), "\n")
	return withoutHTTP + "\n" + registryHTTPBlock(tls), nil
}

// registriesTLSCert mints the TLS cert the registries serve in TLS mode by
// driving the secrets.lok8s.dev Secret plugin — the BINARY lok8s already
// ships and requires (bash: lo::registries_tls_cert). The cert is a `cert:`
// leaf whose SANs are built from .registries.json so it covers every
// registry IP plus the framework hostnames; the plugin signs it with the
// shared dev CA at CAROOT (created on demand) and tls.crt/tls.key are
// extracted to .secrets/tls/registries/ for the container mounts.
//
// TODO(go-port): internal/secrets exists, but the plugin binary IS the
// source of the cert: generator (leaf cache, CA handling) — this stays an
// exec of the same binary until the generator itself is unified into
// internal/secrets. Do not inline a second cert mint path.
//
// Idempotent: re-minted only when missing or when the SAN set changed (IPs
// shifted, a mirror added/removed). The host Docker client + containerd
// trust it once `lo trust` has installed the CA.
func (d *Driver) registriesTLSCert(ctx context.Context, errOut io.Writer) error {
	rf, err := regFile()
	if err != nil {
		return err
	}
	if !rf.TLS {
		return nil
	}

	pluginHome := envOr("KUSTOMIZE_PLUGIN_HOME", filepath.Join(d.deps.Paths.Base, ".kustomize"))
	pluginBin := filepath.Join(pluginHome, "secrets.lok8s.dev", "v1", "secret", "Secret")
	// The Secret plugin mints the cert. It's needed across the lok8s flow
	// anyway, so build it on demand if it's missing and we can (bash probed
	// `declare -F kustomize::build`; the Go seam is the injectable hook);
	// otherwise fail with guidance.
	if !isExecutable(pluginBin) && d.Hooks.KustomizeBuild != nil {
		ui.Debugf(errOut, "registry TLS: Secret plugin missing — building it (lo kustomize build)")
		_ = d.Hooks.KustomizeBuild(ctx)
	}
	if !isExecutable(pluginBin) {
		fmt.Fprintln(errOut, "error: spec.registries.tls is true (default) but the Secret plugin is not built at")
		fmt.Fprintf(errOut, "       %s. Build it with 'lo kustomize build' (needs go), or set\n", pluginBin)
		fmt.Fprintln(errOut, "       spec.registries.tls: false for plain-HTTP registries. Then retry.")
		return fmt.Errorf("secret plugin not built at %s", pluginBin)
	}
	pathSecrets := getenv("PATH_SECRETS")
	if pathSecrets == "" {
		fmt.Fprintln(errOut, "error: PATH_SECRETS is not set — cannot mint the registry TLS cert")
		return fmt.Errorf("PATH_SECRETS not set")
	}

	tlsDir := filepath.Join(d.deps.Paths.Base, ".secrets", "tls", "registries")
	crt := filepath.Join(tlsDir, "tls.crt")
	key := filepath.Join(tlsDir, "tls.key")
	sansFile := filepath.Join(tlsDir, ".sans")
	if err := os.MkdirAll(tlsDir, 0o755); err != nil {
		return err
	}

	// Build the SAN list (hostnames first per entry, then its IP). Framework
	// registries contribute their canonical hostname; mirrors contribute the
	// upstream domain they impersonate. Every registry contributes its IP.
	var sans []string
	for _, r := range rf.Registries {
		if r.Host != "" {
			sans = append(sans, r.Host)
		}
		if r.Domain != "" {
			sans = append(sans, r.Domain)
		}
		if r.IP != "" {
			sans = append(sans, r.IP)
		}
	}
	if len(sans) == 0 {
		fmt.Fprintln(errOut, "error: no registry SANs resolved — cannot mint registry TLS cert")
		return fmt.Errorf("no registry SANs")
	}

	// Deduplicate while preserving order.
	seen := map[string]bool{}
	var uniq []string
	for _, s := range sans {
		if seen[s] {
			continue
		}
		seen[s] = true
		uniq = append(uniq, s)
	}

	// Up to date? (cert present and the SAN set unchanged since the last
	// mint — the .sans cache file is the comparison key.)
	sansRepr := strings.Join(uniq, "\n")
	if fileExists(crt) && fileExists(key) && fileExists(sansFile) {
		if prev, err := os.ReadFile(sansFile); err == nil &&
			strings.TrimRight(string(prev), "\n") == sansRepr {
			ui.Debugf(errOut, "registry TLS cert up to date (%d SANs)", len(uniq))
			return nil
		}
	}

	// (Re)mint. The cert: generator caches its leaf by Secret name, so drop
	// any stale cache entry first to force a fresh signature for the new SAN
	// set.
	name, ns := "registries-tls", "lok8s-system"
	_ = os.Remove(filepath.Join(pathSecrets, fmt.Sprintf("Secret.%s.%s.tls.crt", name, ns)))
	_ = os.Remove(filepath.Join(pathSecrets, fmt.Sprintf("Secret.%s.%s.tls.key", name, ns)))

	// JSON array of SANs (compact, jq -c shape); YAML accepts it inline.
	var hostsJSON strings.Builder
	hostsJSON.WriteByte('[')
	for i, s := range uniq {
		if i > 0 {
			hostsJSON.WriteByte(',')
		}
		fmt.Fprintf(&hostsJSON, "%q", s)
	}
	hostsJSON.WriteByte(']')

	manifest := fmt.Sprintf(`apiVersion: secrets.lok8s.dev/v1
kind: Secret
metadata:
  name: %s
  namespace: %s
type: kubernetes.io/tls
cert:
  hosts: %s
`, name, ns, hostsJSON.String())

	var out strings.Builder
	if err := d.deps.Runner.Run(ctx, execx.Cmd{
		Name:   pluginBin, // absolute path — used as-is by the runner
		Stdin:  strings.NewReader(manifest),
		Stdout: &out,
		Stderr: d.stderr(),
	}); err != nil {
		fmt.Fprintln(errOut, "error: the Secret plugin failed to mint the registry TLS cert")
		return fmt.Errorf("secret plugin failed: %w", err)
	}

	var secretOut struct {
		Data map[string]string `yaml:"data"`
	}
	_ = yaml.Unmarshal([]byte(out.String()), &secretOut)
	crtB64 := secretOut.Data["tls.crt"]
	keyB64 := secretOut.Data["tls.key"]
	if crtB64 == "" || keyB64 == "" {
		fmt.Fprintln(errOut, "error: registry TLS cert extraction failed (plugin output had no tls.crt/tls.key)")
		return fmt.Errorf("secret plugin output missing tls.crt/tls.key")
	}
	crtRaw, err := base64.StdEncoding.DecodeString(crtB64)
	if err != nil {
		fmt.Fprintln(errOut, "error: registry TLS cert extraction failed (plugin output had no tls.crt/tls.key)")
		return err
	}
	keyRaw, err := base64.StdEncoding.DecodeString(keyB64)
	if err != nil {
		fmt.Fprintln(errOut, "error: registry TLS cert extraction failed (plugin output had no tls.crt/tls.key)")
		return err
	}
	if err := os.WriteFile(crt, crtRaw, 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(key, keyRaw, 0o600); err != nil {
		return err
	}
	if err := os.WriteFile(sansFile, []byte(sansRepr+"\n"), 0o644); err != nil {
		return err
	}
	ui.Debugf(errOut, "minted registry TLS cert with SANs: %s", strings.Join(uniq, " "))
	return nil
}

// registriesTLSNudge warns (non-fatally) if registry TLS is on but the dev
// CA isn't trusted by this host yet (bash: lo::registries_tls_nudge). The
// cluster and in-cluster pulls work regardless (containerd trusts via the
// explicit certs.d CA file); only host `docker push` (the Tilt build loop)
// validates against the system trust store, so it fails until the CA is
// trusted. Detection is best-effort: `openssl verify` checks the same host
// store the Docker daemon uses.
//
// Advisory only — every path returns nil; the CALLER's explicit success
// return is what keeps this from deciding the provision's verdict.
func (d *Driver) registriesTLSNudge(ctx context.Context, errOut io.Writer) {
	rf, err := regFile()
	if err != nil || !rf.TLS {
		return
	}
	if _, ok := execx.Look(d.deps.Paths, "openssl"); !ok {
		return // can't check → stay quiet
	}

	caroot := getenv("CAROOT")
	if caroot == "" {
		data := getenv("XDG_DATA_HOME")
		if data == "" {
			data = getenv("HOME") + "/.local/share"
		}
		caroot = data + "/mkcert"
	}
	ca := filepath.Join(caroot, "rootCA.pem")
	if fileExists(ca) && d.runQuiet(ctx, "openssl", "verify", ca) == nil {
		return // CA is in the host trust store → host pushes will verify
	}

	ui.Warnf(errOut, "Registry TLS is on, but this machine doesn't trust the dev CA yet —")
	ui.Warnf(errOut, "  in-cluster pulls work, but 'docker push' to the build registry will fail.")
	ui.Warnf(errOut, "  Fix it once:  lo trust   (or insecure-registries / a rootless runtime)")
	ui.Warnf(errOut, "  How: https://lok8s.io/guide/shared-registries#host-push-trust-options")
}

// registryIPHolder returns the name of the container currently holding ip on
// network, "" when free (bash: lo::registry_ip_holder). IPv4Address carries
// the /prefix, so the match is "<ip>/" as a PREFIX — never .2 matching .20.
func (d *Driver) registryIPHolder(ctx context.Context, network, ip string) string {
	out, _ := d.output(ctx, "docker", "network", "inspect", network,
		"-f", `{{range .Containers}}{{.IPv4Address}} {{.Name}}{{"\n"}}{{end}}`)
	for _, line := range strings.Split(out, "\n") {
		fields := strings.Fields(line)
		if len(fields) >= 2 && strings.HasPrefix(fields[0], ip+"/") {
			return fields[1]
		}
	}
	return ""
}

// registries reconciles every registry container to its desired state
// (bash: lo::registries). Idempotent: a RUNNING container whose config-hash
// label matches is left alone; drift (config, image, address, TLS cert) or
// a dead container means recreate. Emits kubectl-style "registry/<name>
// <verb>" progress lines so callers can wrap it in kapply.Run for the
// collapsing services-style UI. One registry failing does NOT abort the
// rest — errors are surfaced and the function returns non-nil at the end.
func (d *Driver) registries(ctx context.Context, out, errOut io.Writer, domain, clusterYAML string) error {
	registryConfigDir := filepath.Join(d.deps.Paths.Lok8s, "drivers", "lo", "cluster", "registry")

	rf, err := regFile()
	if err != nil {
		return err
	}

	// In TLS mode every registry container mounts the shared cert minted by
	// registriesTLSCert (which must run first — it does, in Provision). The
	// cert content feeds the config hash: registries read it once at
	// startup, so a re-minted cert (SAN change) must recreate the
	// containers.
	var tlsMountArgs []string
	certSig := ""
	if rf.TLS {
		certDir := filepath.Join(d.deps.Paths.Base, ".secrets", "tls", "registries")
		if !fileExists(filepath.Join(certDir, "tls.crt")) || !fileExists(filepath.Join(certDir, "tls.key")) {
			fmt.Fprintf(errOut, "error: spec.registries.tls is enabled but no cert at %s\n", certDir)
			fmt.Fprintln(errOut, "       lo::registries_tls_cert must run before lo::registries (ensure the")
			fmt.Fprintln(errOut, "       Secret plugin is built: lo kustomize build).")
			return fmt.Errorf("registry TLS cert missing at %s", certDir)
		}
		tlsMountArgs = []string{"--volume", certDir + ":" + RegistryTLSMount + ":ro"}
		raw, err := os.ReadFile(filepath.Join(certDir, "tls.crt"))
		if err != nil {
			return err
		}
		certSig = fmt.Sprintf("%x", sha256.Sum256(raw))
	}

	if err := os.MkdirAll(registryStateDir(), 0o755); err != nil {
		return err
	}

	failed := false
	for _, r := range rf.Registries {
		regName, regNetwork := rf.containerFor(r.Name)

		configFile := filepath.Join(registryConfigDir, r.Name+".yaml")
		if !fileExists(configFile) && r.URL != "" {
			configFile = filepath.Join(registryConfigDir, "mirror.yaml")
		}
		if !fileExists(configFile) {
			fmt.Fprintf(errOut, "error: registry/%s: no config for '%s' at %s\n", regName, r.Name, registryConfigDir)
			failed = true
			continue
		}

		// Render config for the active mode (TLS block swap + mirror URL).
		rendered, err := renderRegistryConfig(configFile, r.URL, rf.TLS)
		if err != nil {
			fmt.Fprintf(errOut, "error: registry/%s: %v\n", regName, err)
			failed = true
			continue
		}

		// Desired-state hash. config_path is part of it: moving
		// LO_REGISTRY_STATE_DIR must recreate containers, or they'd keep a
		// bind to the abandoned path and the vanished-mount failure would
		// return. Same printf '%s\n' … | sha256sum input as the bash.
		configPath := filepath.Join(registryStateDir(), regName+".yaml")
		hashInput := rendered + "\n" + RegistryImage + "\n" + regNetwork + "\n" + r.IP + "\n" + configPath + "\n" + certSig + "\n"
		desiredHash := fmt.Sprintf("%x", sha256.Sum256([]byte(hashInput)))

		// Serialize reconciliation of this registry across concurrent `lo`
		// runs (shared mirrors are host-global). Best-effort: without the
		// lock, two simultaneous runs can race rm/run on the same container
		// — the loser's in-flight container may be removed, healed by the
		// next run.
		release, locked := acquireLock(configPath+".lock", d.sleep)
		if !locked {
			ui.Debugf(errOut, "registry %s: lock wait timed out, proceeding unlocked", regName)
		}
		if err := d.registryReconcile(ctx, out, errOut, regName, regNetwork, r.IP,
			configPath, rendered, desiredHash, tlsMountArgs, rf); err != nil {
			failed = true
		}
		if release != nil {
			release()
		}
	}

	if failed {
		return fmt.Errorf("registry reconcile failed")
	}
	return nil
}

// registryReconcile is the mutating half of the reconcile, run under the
// per-registry lock (bash: _lo_registry_reconcile). Inspects state INSIDE
// the lock so a concurrent run that just (re)created the container is
// observed, not clobbered.
func (d *Driver) registryReconcile(ctx context.Context, out, errOut io.Writer,
	regName, regNetwork, ip, configPath, rendered, desiredHash string,
	tlsMountArgs []string, rf *RegistryFile) error {

	state, err := d.output(ctx, "docker", "inspect", "-f", "{{.State.Status}}", regName)
	if err != nil {
		state = "absent"
	}
	currentHash, _ := d.output(ctx, "docker", "inspect", "-f", `{{index .Config.Labels "lok8s.dev/config-hash"}}`, regName)

	if state == "running" && currentHash == desiredHash {
		fmt.Fprintf(out, "registry/%s unchanged\n", regName)
		return nil
	}

	var verb string
	switch state {
	case "absent":
		verb = "created"
	case "running":
		verb = "configured" // up, but config/image/cert drifted
	default:
		verb = "restarted" // created/exited/dead — recreate
	}

	// Durable config path — the daemon re-binds it on every container
	// restart (see registryStateDir in defaults.go). Guarded: a failed
	// write (read-only dir, disk full) must not proceed to remove a healthy
	// container that would then restart against a stale or missing config.
	if err := os.WriteFile(configPath, []byte(rendered+"\n"), 0o644); err != nil {
		fmt.Fprintf(errOut, "error: registry/%s: cannot write config at %s\n", regName, configPath)
		return fmt.Errorf("cannot write registry config %s", configPath)
	}

	_ = d.runQuiet(ctx, "docker", "volume", "create", regName)
	_ = d.runQuiet(ctx, "docker", "rm", "-f", regName)

	runErr := ""
	for attempt := 1; attempt <= 2; attempt++ {
		args := []string{"run", "-d", "--restart=always", "--name", regName,
			"--label", "lok8s.dev/config-hash=" + desiredHash,
			"--volume", regName + ":/var/lib/registry",
			"--volume", configPath + ":/config.yaml:ro"}
		args = append(args, tlsMountArgs...)
		args = append(args, "--net="+regNetwork, "--ip", ip, RegistryImage, "/config.yaml")
		errText, err := d.errOutput(ctx, "docker", args...)
		if err == nil {
			fmt.Fprintf(out, "registry/%s %s\n", regName, verb)
			return nil
		}
		runErr = errText
		// Lost a race with a concurrent `lo` run despite best-effort
		// locking: the other run winning IS the desired state.
		if st, _ := d.output(ctx, "docker", "inspect", "-f", "{{.State.Status}}", regName); st == "running" {
			fmt.Fprintf(out, "registry/%s unchanged\n", regName)
			return nil
		}
		// Don't leave a half-created container behind — `docker run`
		// creates it even when the start fails, and a stuck-Created
		// container shadows the name on the next attempt.
		_ = d.runQuiet(ctx, "docker", "rm", "-f", regName)
		if attempt == 2 {
			break
		}
		// One bounded retry for a transiently-held address: the endpoint of
		// the container we just removed can lag its release. A PERSISTENT
		// holder should be impossible on a range-reserved network
		// (registryNetwork recreates legacy ones) — if one appears anyway,
		// fail loudly with the holder named rather than shuffling someone
		// else's container.
		if strings.Contains(strings.ToLower(runErr), "address already in use") {
			holder := d.registryIPHolder(ctx, regNetwork, ip)
			if holder != "" {
				fmt.Fprintf(errOut, "error: registry/%s: %s is held by '%s' on '%s'.\n", regName, ip, holder, regNetwork)
				if regNetwork == rf.Network.Name {
					// Shared net: recreating it (which reserves the dynamic
					// range) is always the fix — clean detaches any holder.
					fmt.Fprintln(errOut, "error: recreate the shared network: lo registry clean --shared && lo up")
				} else {
					// Project net (legacy, created before its reserved
					// range): the holder is almost always a kind node that
					// grabbed the address after a host reboot. Detaching a
					// live node changes its address (lo up heals the node-ip
					// afterwards); recreating the cluster rebuilds the
					// network WITH the range.
					fmt.Fprintf(errOut, "error: a kind node likely grabbed this address after a reboot — run: docker network disconnect -f %s %s && lo up\n", regNetwork, holder)
					fmt.Fprintf(errOut, "error: (or recreate the cluster — 'lo down && lo up' — to rebuild '%s' with its reserved dynamic range)\n", regNetwork)
				}
				return fmt.Errorf("registry %s address %s squatted by %s", regName, ip, holder)
			}
			d.sleepSeconds(1)
		} else {
			break
		}
	}

	fmt.Fprintf(errOut, "error: registry/%s: %s\n", regName, runErr)
	return fmt.Errorf("registry %s failed to start", regName)
}

// applyLocalRegistryHosting applies the KEP-1755 local-registry-hosting
// ConfigMap (bash: lo::apply_local_registry_hosting). Missing prerequisites
// are WARNINGS, never failures — the cluster works without the hint CM.
func (d *Driver) applyLocalRegistryHosting(ctx context.Context, out, errOut io.Writer, domain string) error {
	clusterYAML := filepath.Join(d.deps.Paths.Clusters, domain, "cluster.lok8s.yaml")
	clusterName := yqRaw(loadYAML(clusterYAML), "metadata", "name")
	if clusterName == "null" {
		clusterName = ""
	}
	kubeconfig := filepath.Join(d.deps.Paths.Base, ".kubeconfig", clusterName+".yaml")
	if !fileExists(kubeconfig) {
		fmt.Fprintf(errOut, "warning: no kubeconfig at %s, skipping local-registry-hosting\n", kubeconfig)
		return nil
	}

	rf, err := regFile()
	if err != nil {
		return err
	}
	buildIP := rf.get("build", "ip")
	buildHost := rf.get("build", "host")
	if buildIP == "" {
		fmt.Fprintln(errOut, "warning: build registry IP unknown, skipping local-registry-hosting")
		return nil
	}
	if buildHost == "" {
		buildHost = "lok8s.local"
	}

	manifest := fmt.Sprintf(`apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
  namespace: kube-public
  labels:
    lok8s.dev/type: system
data:
  localRegistryHosting.v1: |
    host: "%s"
    hostFromClusterNetwork: "%s"
    help: "https://kernpilot.github.io/lok8s/guide/services#how-the-image-swap-actually-works"
`, buildIP, buildHost)
	return d.runInput(ctx, manifest, out, errOut, "kubectl", "apply", "--kubeconfig", kubeconfig, "-f", "-")
}

// cleanupRegistries removes the project's registry containers + volumes +
// durable configs, SKIPPING shared mirrors — they persist across project
// lifecycles (bash: lo::cleanup_registries).
func (d *Driver) cleanupRegistries(ctx context.Context, clusterName string) {
	_ = clusterName // the bash accepted it for symmetry; container names come from the JSON
	rf, err := regFile()
	if err != nil {
		return
	}
	for _, r := range rf.Registries {
		if rf.Shared && r.Type == "mirror" {
			continue
		}
		regName, _ := rf.containerFor(r.Name)
		_ = d.runQuiet(ctx, "docker", "rm", "-f", regName)
		_ = d.runQuiet(ctx, "docker", "volume", "rm", "-f", regName)
		removeStateFiles(regName)
	}
}

// removeStateFiles drops a registry's durable config + lock file (the same
// paths the bash rm -f'd).
func removeStateFiles(regName string) {
	_ = os.Remove(filepath.Join(registryStateDir(), regName+".yaml"))
	_ = os.Remove(filepath.Join(registryStateDir(), regName+".yaml.lock"))
}

// registryConfigmap applies the lok8s-registries ConfigMap consumed
// in-cluster (bash: lo::registry_configmap).
func (d *Driver) registryConfigmap(ctx context.Context, out, errOut io.Writer, domain, clusterYAML string) error {
	clusterName := yqRaw(loadYAML(clusterYAML), "metadata", "name")
	if clusterName == "null" {
		clusterName = ""
	}
	kubeconfig := filepath.Join(d.deps.Paths.Base, ".kubeconfig", clusterName+".yaml")

	rf, err := regFile()
	if err != nil {
		return err
	}

	// Build the ConfigMap data block exactly like the bash jq -r program:
	// each registry emits a multi-line string that itself ends in "\n", and
	// jq -r appends another newline per result — so entries are separated by
	// BLANK lines, and the $() capture strips the trailing run. Reproduced
	// byte-for-byte; YAML tolerates the blank lines.
	var blocks []string
	for _, r := range rf.Registries {
		var b strings.Builder
		fmt.Fprintf(&b, "  %s.ip: \"%s\"\n", r.Name, r.IP)
		// KNOWN DEFECT, PRESERVED ON PURPOSE: the port is hardcoded "5000" —
		// the registries actually listen on 80/443 (TLS-mode-dependent, see
		// defaults.go). The bash jq wrote "5000" since day one and in-cluster
		// consumers may compensate; fixing it is a coordinated change with
		// them, not a port side-effect. Do NOT silently correct.
		fmt.Fprintf(&b, "  %s.port: \"5000\"\n", r.Name)
		if r.URL != "" {
			fmt.Fprintf(&b, "  %s.url: \"%s\"\n", r.Name, r.URL)
		}
		if r.Type == "mirror" {
			fmt.Fprintf(&b, "  %s.shared: \"true\"\n", r.Name)
		}
		blocks = append(blocks, b.String())
	}
	configmapData := strings.TrimRight(strings.Join(blocks, "\n"), "\n")

	manifest := fmt.Sprintf(`apiVersion: v1
kind: ConfigMap
metadata:
  name: lok8s-registries
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: lok8s
data:
%s
`, configmapData)
	return d.runInput(ctx, manifest, out, errOut, "kubectl", "apply", "--kubeconfig", kubeconfig, "-f", "-")
}

func isExecutable(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir() && info.Mode()&0o111 != 0
}
