# HCloud machine template for cloud VMs
# Rendered per control plane and per worker pool
# Variables: ${MACHINE_TEMPLATE_NAME}, ${MACHINE_TYPE}, ${HCLOUD_REGION}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: ${MACHINE_TEMPLATE_NAME}
  namespace: ${CLUSTER_NAMESPACE}
  labels:
    lok8s.dev/managed: "true"
    lok8s.dev/domain: ${CLUSTER_DOMAIN}
spec:
  template:
    spec:
      type: ${MACHINE_TYPE}
      imageName: ${MACHINE_IMAGE_NAME}
