// Package htpasswdfmt formats apache-htpasswd entries using bcrypt.
//
// Bcrypt is the only supported hash format. It's the modern default for
// apache htpasswd (`htpasswd -B`), is supported by every web server,
// and is the only format with a reasonable security margin in 2026.
//
// Cost factor is 10 (apache default). Salts are generated by
// golang.org/x/crypto/bcrypt and are non-deterministic, so the cache
// layer is responsible for storing the hashed line so output is byte-
// stable across runs (see plugins/secret/generator/htpasswd.go).
package htpasswdfmt

import (
	"fmt"

	"golang.org/x/crypto/bcrypt"
)

// DefaultCost is the bcrypt cost factor used for new hashes.
const DefaultCost = 10

// Format builds an htpasswd line for the given username and plaintext
// password using bcrypt at DefaultCost. The returned bytes are a single
// line of the form "username:$2y$10$<salt><hash>" without a trailing
// newline.
//
// The username must not contain ':' (which would corrupt the format).
// The password may be any byte sequence (bcrypt truncates at 72 bytes,
// which is documented).
func Format(username string, password []byte) ([]byte, error) {
	return FormatCost(username, password, DefaultCost)
}

// FormatCost is Format with an explicit bcrypt cost. Use only when
// testing or when an explicit cost override is required.
func FormatCost(username string, password []byte, cost int) ([]byte, error) {
	if username == "" {
		return nil, fmt.Errorf("htpasswdfmt: username must not be empty")
	}
	if containsByte(username, ':') {
		return nil, fmt.Errorf("htpasswdfmt: username must not contain ':'")
	}
	hash, err := bcrypt.GenerateFromPassword(password, cost)
	if err != nil {
		return nil, fmt.Errorf("htpasswdfmt: bcrypt: %w", err)
	}
	return fmt.Appendf(nil, "%s:%s", username, hash), nil
}

// Verify checks that an htpasswd line matches the given plaintext
// password. Returns nil on match, an error on mismatch or malformed line.
func Verify(line []byte, password []byte) error {
	colon := indexByte(line, ':')
	if colon < 0 {
		return fmt.Errorf("htpasswdfmt: malformed line (no ':')")
	}
	hash := line[colon+1:]
	return bcrypt.CompareHashAndPassword(hash, password)
}

func containsByte(s string, b byte) bool {
	for i := 0; i < len(s); i++ {
		if s[i] == b {
			return true
		}
	}
	return false
}

func indexByte(s []byte, b byte) int {
	for i, c := range s {
		if c == b {
			return i
		}
	}
	return -1
}
