events { worker_connections 4096; }
http {
  server {
    listen 443 ssl http2;
    server_name *.${LOK8S_EXPOSE_DOMAIN};

    ssl_certificate /tls.cert;
    ssl_certificate_key /tls.key;

    location / {
      proxy_pass https://${LOK8S_EXPOSE_BACKEND_IP};
      proxy_ssl_server_name on;
      proxy_ssl_name $host;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }
  }
  server {
    listen 80;
    server_name *.${LOK8S_EXPOSE_DOMAIN};
    return 301 https://$host$request_uri;
  }
}
