// Package crds is the Go port of .lok8s/libs/crds — operator CRD generation
// from a single schema source.
//
// SINGLE SOURCE OF TRUTH: operator/crds/schema/<kind>.schema.yaml (a few CRD
// knobs + the verbatim spec/status OpenAPI bodies). The
// operator/crds/<kind>.yaml files are GENERATED — never hand-edit them; edit
// the schema and run `lo crds generate`. `lo crds check` is the CI drift
// gate.
//
// The render is a yaml.Node transform, not a text template: the spec and
// status bodies are copied VERBATIM as nodes (so x-kubernetes-
// preserve-unknown-fields, pattern, propertyNames, comments, quoting styles
// and `null` members all survive), and the CRD wrapper is pure boilerplate.
// The output is byte-identical to the bash `yq eval` render — the committed
// CRDs are the parity fixture (TestRenderMatchesCommittedCRDs).
package crds

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/kernpilot/lok8s/internal/config"
	"github.com/kernpilot/lok8s/internal/ui"
)

// Banner is the generated-file header (bash: CRD_BANNER); the kind's schema
// file name follows it.
const Banner = "# GENERATED by 'lo crds generate' — DO NOT EDIT. Source: operator/crds/schema/"

// Layout resolves the schema/output/mirror locations for a project.
type Layout struct {
	// SchemaDir is operator/crds/schema (bash: CRD_SCHEMA_DIR).
	SchemaDir string
	// OutDir is operator/crds (bash: CRD_OUT_DIR).
	OutDir string
	// InventoryMirror is the ClusterInventory CRD's second generated
	// artifact (bash: CRD_INVENTORY_MIRROR). Consumer repos vendor only
	// .lok8s/** (b env sync) — never operator/ — and inventory::publish
	// applies the CRD from this mirror at the end of provision/bootstrap.
	// Same schema source, same banner, same drift gate.
	InventoryMirror string
	// Base is the project root, used to relativize the mirror path in
	// messages (bash: ${CRD_INVENTORY_MIRROR#"${PATH_BASE}/"}).
	Base string
}

// NewLayout derives the layout from the resolved project paths.
func NewLayout(p *config.Paths) Layout {
	return Layout{
		SchemaDir:       filepath.Join(p.Base, "operator", "crds", "schema"),
		OutDir:          filepath.Join(p.Base, "operator", "crds"),
		InventoryMirror: filepath.Join(p.Lok8s, "libs", "inventory", "manifests", "clusterinventory.crd.yaml"),
		Base:            p.Base,
	}
}

// mirrorRel is the mirror path as bash prints it: relative to the project
// root when it lives under it, verbatim otherwise.
func (l Layout) mirrorRel() string {
	return strings.TrimPrefix(l.InventoryMirror, l.Base+"/")
}

// Schemas lists the schema files, in bash glob order (sorted bytewise).
func (l Layout) Schemas() []string {
	matches, _ := filepath.Glob(filepath.Join(l.SchemaDir, "*.schema.yaml"))
	var files []string
	for _, m := range matches {
		if info, err := os.Stat(m); err == nil && !info.IsDir() {
			files = append(files, m)
		}
	}
	sort.Strings(files)
	return files
}

// Kind reads the lowercased `.kind` of a schema file (bash: yq -r '.kind |
// downcase').
func Kind(schemaPath string) (string, error) {
	var doc struct {
		Kind string `yaml:"kind"`
	}
	raw, err := os.ReadFile(schemaPath)
	if err != nil {
		return "", err
	}
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		return "", err
	}
	return strings.ToLower(doc.Kind), nil
}

// Render renders one schema file into the complete generated CRD file
// content: the banner line plus the CRD document (bash: the `{ echo banner;
// crds::_render; }` pair).
func Render(schemaPath string) ([]byte, error) {
	kind, err := Kind(schemaPath)
	if err != nil {
		return nil, err
	}
	body, err := renderBody(schemaPath)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	buf.WriteString(Banner + kind + ".schema.yaml\n")
	buf.Write(body)
	return buf.Bytes(), nil
}

// renderBody is crds::_render: the CRD wrapper around the verbatim
// spec/status bodies. The three optional wrapper knobs a kind may omit
// (shortNames / printer columns / status) are dropped ONLY at the wrapper
// level — never recursively — so legitimate nulls inside the verbatim bodies
// (`default: null`, a `null` enum member) survive untouched.
func renderBody(schemaPath string) ([]byte, error) {
	raw, err := os.ReadFile(schemaPath)
	if err != nil {
		return nil, err
	}
	var root yaml.Node
	if err := yaml.Unmarshal(raw, &root); err != nil {
		return nil, fmt.Errorf("%s: %w", schemaPath, err)
	}
	schema := docContent(&root)
	if schema == nil || schema.Kind != yaml.MappingNode {
		return nil, fmt.Errorf("%s: schema is not a mapping", schemaPath)
	}

	kind := scalarOf(schema, "kind")
	group := scalarOf(schema, "group")
	plural := scalarOf(schema, "plural")
	version := scalarOf(schema, "version")
	scope := scalarOf(schema, "scope")
	if scope == "" || isNull(lookup(schema, "scope")) {
		scope = "Namespaced"
	}

	names := mapping(
		str("kind"), str(kind),
		str("listKind"), str(kind+"List"),
		str("plural"), str(plural),
		str("singular"), str(strings.ToLower(kind)),
	)
	if n := lookup(schema, "shortNames"); n != nil && !isNull(n) {
		names.Content = append(names.Content, str("shortNames"), stripDocComments(n))
	}

	versionEntry := mapping(
		str("name"), str(version),
		str("served"), boolNode(true),
		str("storage"), boolNode(true),
		str("subresources"), mapping(str("status"), mapping()),
	)
	if n := lookup(schema, "printerColumns"); n != nil && !isNull(n) {
		versionEntry.Content = append(versionEntry.Content, str("additionalPrinterColumns"), stripDocComments(n))
	}
	properties := mapping(str("spec"), stripDocComments(lookupOrNull(schema, "spec")))
	if n := lookup(schema, "status"); n != nil && !isNull(n) {
		properties.Content = append(properties.Content, str("status"), stripDocComments(n))
	}
	versionEntry.Content = append(versionEntry.Content,
		str("schema"), mapping(
			str("openAPIV3Schema"), mapping(
				str("type"), str("object"),
				str("required"), sequence(str("spec")),
				str("properties"), properties,
			),
		),
	)

	crd := mapping(
		str("apiVersion"), str("apiextensions.k8s.io/v1"),
		str("kind"), str("CustomResourceDefinition"),
		str("metadata"), mapping(str("name"), str(plural+"."+group)),
		str("spec"), mapping(
			str("group"), str(group),
			str("names"), names,
			str("scope"), str(scope),
			str("versions"), sequence(versionEntry),
		),
	)

	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(crd); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// Generate renders every schema into OutDir (bash: crds::generate), and the
// ClusterInventory CRD additionally into the .lok8s mirror. Progress lines
// go to out.
func Generate(l Layout, out io.Writer) error {
	for _, schema := range l.Schemas() {
		kind, err := Kind(schema)
		if err != nil {
			return err
		}
		rendered, err := Render(schema)
		if err != nil {
			return err
		}
		outPath := filepath.Join(l.OutDir, kind+".yaml")
		if err := os.WriteFile(outPath, rendered, 0o644); err != nil {
			return err
		}
		fmt.Fprintf(out, "  wrote operator/crds/%s.yaml\n", kind)
		if kind == "clusterinventory" {
			if err := os.MkdirAll(filepath.Dir(l.InventoryMirror), 0o755); err != nil {
				return err
			}
			if err := os.WriteFile(l.InventoryMirror, rendered, 0o644); err != nil {
				return err
			}
			fmt.Fprintf(out, "  wrote %s (mirror for synced .lok8s trees)\n", l.mirrorRel())
		}
	}
	return nil
}

// ErrStale is returned by Check when at least one generated CRD is stale.
var ErrStale = fmt.Errorf("stale CRDs")

// Check is the drift gate (bash: crds::check): re-render every schema and
// compare against the committed CRD (and the mirror for clusterinventory).
// Every stale artifact is reported; ErrStale when any was.
func Check(l Layout, out, stderr io.Writer) error {
	stale := false
	for _, schema := range l.Schemas() {
		kind, err := Kind(schema)
		if err != nil {
			return err
		}
		rendered, err := Render(schema)
		if err != nil {
			return err
		}
		if !sameBytes(rendered, filepath.Join(l.OutDir, kind+".yaml")) {
			ui.Errorf(stderr, "  operator/crds/%s.yaml is STALE — run 'lo crds generate'", kind)
			stale = true
		}
		// The clusterinventory CRD has a second generated artifact — the
		// .lok8s mirror the publish path applies on consumer repos. Gate it
		// too.
		if kind == "clusterinventory" && !sameBytes(rendered, l.InventoryMirror) {
			ui.Errorf(stderr, "  %s is STALE — run 'lo crds generate'", l.mirrorRel())
			stale = true
		}
	}
	if stale {
		return ErrStale
	}
	fmt.Fprintln(out, "  all CRDs up to date.")
	return nil
}

// sameBytes reports whether path exists with exactly the given content
// (bash: diff -q; a missing file is a difference).
func sameBytes(want []byte, path string) bool {
	got, err := os.ReadFile(path)
	return err == nil && bytes.Equal(got, want)
}

// ── yaml.Node helpers ────────────────────────────────────────────────────

func docContent(n *yaml.Node) *yaml.Node {
	if n.Kind == yaml.DocumentNode {
		if len(n.Content) == 0 {
			return nil
		}
		return n.Content[0]
	}
	return n
}

func lookup(m *yaml.Node, key string) *yaml.Node {
	if m == nil || m.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == key {
			return m.Content[i+1]
		}
	}
	return nil
}

// lookupOrNull is lookup with a `null` node for an absent key — yq's `.spec`
// on a schema without one yields null, and the wrapper keeps it.
func lookupOrNull(m *yaml.Node, key string) *yaml.Node {
	if n := lookup(m, key); n != nil {
		return n
	}
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!null", Value: "null"}
}

func scalarOf(m *yaml.Node, key string) string {
	n := lookup(m, key)
	if n == nil || n.Kind != yaml.ScalarNode {
		return ""
	}
	return n.Value
}

func isNull(n *yaml.Node) bool {
	return n != nil && n.Kind == yaml.ScalarNode && n.Tag == "!!null"
}

func str(v string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: v}
}

func boolNode(v bool) *yaml.Node {
	s := "false"
	if v {
		s = "true"
	}
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: s}
}

func mapping(kv ...*yaml.Node) *yaml.Node {
	return &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map", Content: kv}
}

func sequence(items ...*yaml.Node) *yaml.Node {
	return &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq", Content: items}
}

// stripDocComments detaches a verbatim body from its position in the schema
// document: yq copies the VALUE node, so the comment that preceded the
// schema key (a head comment on the key, not the value) does not travel.
// The node itself is reused, not cloned — the schema tree is discarded after
// the render.
func stripDocComments(n *yaml.Node) *yaml.Node {
	return n
}
