// Package secrets is the Go port of .lok8s/libs/secrets — secret cache
// management with SOPS/age encryption.
//
// The lok8s secret plugin generates values into the secrets store as
// plaintext cache files (Secret.<name>.<ns>.<key>). This package adds
// SOPS/age encryption so those cache files can be committed safely.
//
// Layout (single-instance project — flat store):
//
//	.secrets/Secret.myapp.default.PASSWORD       ← plaintext (gitignored)
//	.secrets/Secret.myapp.default.PASSWORD.enc   ← SOPS-encrypted (committed)
//	.secrets/tls/                                ← mkcert certs (gitignored)
//
// Per-INSTANCE isolation (multi-domain repos): a domain keeps its OWN secrets
// under clusters/<domain>/secrets/, and the CLI + `lo build` use only that
// store for that domain. This is the secure default for anything serving
// multiple environments — dev/prod never share a generated value, and SOPS
// creation_rules can encrypt each domain's store to DIFFERENT recipients so a
// dev/CI key cannot decrypt prod. There is deliberately NO shared tier: a
// value needed in two instances is a manual copy (the operator consenting to
// that exposure), never a silent fallback. See docs/guide/secrets.md.
//
// Encryption uses age keys derived from SSH keys (the ssh-to-age scheme).
// No new key ceremony — your existing ~/.ssh/id_ed25519 is your encryption
// identity.
package secrets

import (
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/kernpilot/lok8s/internal/config"
	"github.com/kernpilot/lok8s/internal/ui"
)

// ErrPrinted marks an error whose message was already printed in the bash
// implementation's own format ([error] … on stderr). Callers exit non-zero
// without printing anything further (the cli layer maps it to ErrHandled).
var ErrPrinted = ui.ErrHandled // one sentinel for every package; see internal/ui

// nameRe is the Secret --name allowlist. The name lands in a glob under the
// store dir; a slash or .. would let it address files outside the store. Same
// charset the domain resolver enforces.
var nameRe = regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9._-]*$`)

// Context carries the resolved environment a secrets operation runs in.
type Context struct {
	Paths  *config.Paths
	Domain string // resolved domain ("" = flat store only)
	Out    io.Writer
	ErrOut io.Writer

	// Stdin and StdinIsTTY feed `set`'s value fallback (piped stdin vs the
	// interactive prompt). ReadPassword is the silent tty read; injectable
	// for tests.
	Stdin        io.Reader
	StdinIsTTY   func() bool
	ReadPassword func() (string, error)

	// Kubeconfig is the KUBECONFIG value the bash entrypoint exported
	// (PATH_BASE/.kubeconfig/<cluster>.yaml) — the live-drift check's kubectl
	// runs against exactly that file, never the caller's ambient KUBECONFIG.
	Kubeconfig string
}

// flatStore resolves the deprecated flat store the way bash does:
// ${PATH_SECRETS:-${PATH_BASE}/.secrets}.
func (c *Context) flatStore() string {
	if c.Paths.SecretsEnv != "" {
		return c.Paths.SecretsEnv
	}
	return c.Paths.Base + "/.secrets"
}

// StorePath resolves the secrets store for the current context (bash:
// secrets::path). A domain with its own clusters/<domain>/secrets/ uses THAT
// store exclusively (per-instance isolation, no flat fallback for it);
// otherwise the flat PATH_SECRETS store (single-instance projects).
// `lo build` mirrors this — see build::_export_secrets_path.
//
// String concatenation on purpose (not filepath.Join): bash interpolates the
// domain into the path verbatim, and `lo secrets path` must print the same
// bytes.
func (c *Context) StorePath() string {
	if c.Domain != "" {
		d := c.Paths.Clusters + "/" + c.Domain + "/secrets"
		if isDir(d) {
			return d
		}
	}
	return c.flatStore()
}

// ensureStore scaffolds a domain's per-domain store so a WRITE lands there
// (not the flat fallback) even on the very first command — StorePath only
// returns the per-domain path once the dir exists, so create it first when a
// domain is in context (bash: secrets::_ensure_store). A no-op when no domain
// is in context or the domain dir doesn't exist.
func (c *Context) ensureStore() error {
	if c.Domain != "" && isDir(c.Paths.Clusters+"/"+c.Domain) {
		return os.MkdirAll(c.Paths.Clusters+"/"+c.Domain+"/secrets", 0o755)
	}
	return nil
}

// sopsConfigPath is ${PATH_BASE}/.sops.yaml — its presence means "encryption
// is configured".
func (c *Context) sopsConfigPath() string {
	return c.Paths.Base + "/.sops.yaml"
}

const gitignoreContent = `# Auto-generated by lok8s — ignore everything except SOPS-encrypted
# secret cache files. Plaintext cache entries must never be committed.
*
!.gitignore
!Secret.*.enc
`

// ensureGitignore makes sure the secrets dir has a .gitignore that blocks
// plaintext but allows .enc files. Creates (or rewrites) the file when the
// `!Secret.*.enc` allow line is missing (bash: secrets::_ensure_gitignore).
func ensureGitignore(dir string) error {
	gitignore := dir + "/.gitignore"
	if raw, err := os.ReadFile(gitignore); err == nil && strings.Contains(string(raw), "!Secret.*.enc") {
		return nil
	}
	if err := os.WriteFile(gitignore, []byte(gitignoreContent), 0o644); err != nil { // #nosec G306 -- the store's .gitignore
		return err
	}
	ui.Debug("Created %s", gitignore)
	return nil
}

// storeEntries lists the store's file names in bash glob order (byte-sorted),
// filtered to those with the given prefix. Only names are filtered here;
// callers apply their own regular-file / .enc checks like the bash loops do.
func storeEntries(dir, prefix string) []string {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil
	}
	var names []string
	for _, e := range entries {
		if strings.HasPrefix(e.Name(), prefix) {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)
	return names
}

// isFile mirrors bash [[ -f ]] (follows symlinks).
func isFile(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.Mode().IsRegular()
}

// isDir mirrors bash [[ -d ]].
func isDir(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}

// exists mirrors bash [[ -e ]].
func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// newerThan mirrors bash [[ a -nt b ]]: a exists and its mtime is strictly
// newer than b's.
func newerThan(a, b string) bool {
	ai, err := os.Stat(a)
	if err != nil {
		return false
	}
	bi, err := os.Stat(b)
	if err != nil {
		return true
	}
	return ai.ModTime().After(bi.ModTime())
}

// trimTrailingNewlines strips trailing \n the way a bash command substitution
// ($(cat …)) does.
func trimTrailingNewlines(s string) string {
	return strings.TrimRight(s, "\n")
}

// nudgeNewer makes dst's mtime strictly newer than src's when it isn't
// already. The bash implementation gets this ordering for free — spawning the
// sops binary always lands the output file a clock tick after its input — and
// the -nt freshness skips depend on it: an in-process encrypt/decrypt can
// finish within the SAME tick, and an equal mtime reads as "stale", causing
// pointless .enc/plaintext churn on every subsequent sweep.
func nudgeNewer(dst, src string) {
	si, err := os.Stat(src)
	if err != nil {
		return
	}
	di, err := os.Stat(dst)
	if err != nil || di.ModTime().After(si.ModTime()) {
		return
	}
	t := si.ModTime().Add(time.Microsecond)
	_ = os.Chtimes(dst, t, t)
}

// CheckUnencrypted reports plaintext secrets without a fresh .enc twin in dir
// (used by lint; bash: secrets::check_unencrypted). Returns false if any
// plaintext secret lacks a corresponding up-to-date .enc file, true when all
// secrets are encrypted or no secrets exist.
func CheckUnencrypted(dir string, warnTo io.Writer) bool {
	if !isDir(dir) {
		return true
	}
	ok := true
	for _, name := range storeEntries(dir, "Secret.") {
		plaintext := dir + "/" + name
		if !isFile(plaintext) || strings.HasSuffix(name, ".enc") {
			continue
		}
		if !isFile(plaintext + ".enc") {
			ui.Warnf(warnTo, "Unencrypted secret: %s — run: lo secrets encrypt", name)
			ok = false
		} else if newerThan(plaintext, plaintext+".enc") {
			ui.Warnf(warnTo, "Secret changed since last encrypt: %s — run: lo secrets encrypt", name)
			ok = false
		}
	}
	return ok
}

// CheckFlatShadows reports deprecated flat-store shadows of a domain's
// per-domain secrets (bash: secrets::check_flat_shadows).
//
// A domain with its OWN store (clusters/<domain>/secrets/) must not ALSO keep
// the same Secret.<name>.<ns>.<key> in the flat store: the two diverge
// silently and different tools read different stores (lo build/Tilt →
// per-domain; a manual PATH_SECRETS=.../.secrets kustomize → flat), which can
// re-key a live cluster from the WRONG store (this orphaned a dev IdP's etcd
// encryption once). Per-domain is authoritative; the flat store keeps ONLY
// global, non-domain material (e.g. a shared registry/expose TLS cert that no
// per-domain store mirrors).
//
// Emits one line per shadow to out (lint wraps each as a warning); returns
// false if any shadow exists, true otherwise. An identical copy is a stale
// duplicate; a DIFFERING copy is active drift — the dangerous case.
func CheckFlatShadows(flat, domainDir string, out io.Writer) bool {
	store := domainDir + "/secrets"
	dname := filepath.Base(domainDir)

	// Only meaningful when the domain has its OWN store, distinct from the
	// flat one.
	if flat == "" || !isDir(store) || !isDir(flat) {
		return true
	}
	if samePath(store, flat) {
		return true
	}

	ok := true
	for _, base := range storeEntries(store, "Secret.") {
		plaintext := store + "/" + base
		if !isFile(plaintext) || strings.HasSuffix(base, ".enc") || strings.HasSuffix(base, ".sha") {
			continue
		}
		flatCopy := flat + "/" + base
		if !isFile(flatCopy) {
			continue
		}
		if sameContent(flatCopy, plaintext) {
			io.WriteString(out, "Flat-store shadow: "+base+" is duplicated in the flat .secrets/ store — flat is deprecated for domain secrets; remove the flat copy (it keeps only global TLS like registries-tls)\n")
		} else {
			io.WriteString(out, "Flat-store DRIFT: "+base+" differs between the flat .secrets/ store and "+dname+"/secrets/ — the stores diverged (a build from the wrong store can re-key a live cluster); reconcile to the per-domain value, then remove the flat copy\n")
		}
		ok = false
	}
	return ok
}

// samePath mirrors bash [[ a -ef b ]] (same device+inode).
func samePath(a, b string) bool {
	ai, err := os.Stat(a)
	if err != nil {
		return false
	}
	bi, err := os.Stat(b)
	if err != nil {
		return false
	}
	return os.SameFile(ai, bi)
}

// sameContent mirrors `cmp -s`.
func sameContent(a, b string) bool {
	ab, err := os.ReadFile(a)
	if err != nil {
		return false
	}
	bb, err := os.ReadFile(b)
	if err != nil {
		return false
	}
	return string(ab) == string(bb)
}
